MyCATApache/Mycat-Server

src/main/java/org/opencloudb/config/loader/xml/XMLSchemaLoader.java
src/main/resources/schema.dtd
src/test/resources/route/schema.xml

支持三种情况的通配符配置：
1.  < dataNode name="dn$1-6" dataHost="test1" database="base$1-6" />
2. < dataNode name="dn$1-6" dataHost="test$1-6" database="base" />
3. < dataNode name="dn$1-6" dataHost="test$1-3" database="base$1-2" />
稍后补充详细用法到文档中

支持dataNode节点的通配符支持

---

src/main/java/org/opencloudb/config/loader/xml/XMLSchemaLoader.java
src/main/java/org/opencloudb/config/model/TableConfig.java
src/main/java/org/opencloudb/parser/druid/DruidParserFactory.java
src/main/java/org/opencloudb/parser/druid/impl/DruidSelectParser.java
src/main/java/org/opencloudb/parser/druid/impl/DruidSelectPostgresqlParser.java

1.修改解析配置TableConfig的dbType时以支持多个dataNode
2.添加postgresql的limit解析转换

修改解析配置TableConfig的dbType时以支持多个dataNode，添加postgresql的limit解析转换

---

src/main/java/org/opencloudb/route/RouteResultsetNode.java

1.  事务内的SQL，默认走写节点，以注释/*balance*/开头，则会根据balance=“1” 或“2” 去获取
2.  非事务内的SQL，开启读写分离默认根据balance=“1” 或“2” 去获取，以注释/*balance*/开头 则会走写
解决部分已经开启读写分离， 但是需要强一致性数据实时获取的场景走写

/*balance*/ 使用规则修改

---

src/main/java/org/opencloudb/config/loader/xml/XMLSchemaLoader.java
src/main/java/org/opencloudb/sequence/handler/IncrSequenceMySQLHandler.java

根据seqName获取自增序列时，如果配置文件没有进行配置，取到的SequenceVal对象在后面的执行中会抛出空指针，对用户不友好，对运维排错也不方便。可以先对对象进行非空验证，抛出序列未定义的异常信息，便于排错。

增加对自增序列的非空判断，如果没有配置，则抛出配置异常，提示没有序列的定义，避免直接抛出空指针异常。

---

src/main/java/io/mycat/route/util/RouterUtil.java

【问题原因】在navicat for mysql等mysql客户端软件中，sql标准格式后以多行形式，这样就会报表名不存在
【解决方法】取表名getTableName方法中，增加判断是否有\n字符

解决mysql客户端中编辑表报表不存在的错误

---

src/main/java/io/mycat/server/executors/MultiNodeQueryHandler.java

[问题原因]select返回条数少于limit时，end=limit则大于返回条数，则for循环取数据报错
[问题修改]end不能大于results.size()，比较end与results.size()

select返回条数少于limit时报错

---

src/main/java/org/opencloudb/mysql/nio/MySQLConnection.java
src/main/resources/myid.properties

后端链接在同步完毕之后才回调修改当前后端链接的字符集,导致第一条发送出去的字符是使用后端链接的字符集进行编码的,而不是真正前端链接的字符集,导致编码出错.

修复:客户端字符集同步不一致.

---

src/main/java/io/mycat/server/config/node/MycatConfig.java
src/main/java/io/mycat/sqlengine/SQLJob.java

之前一直好好的，突然有一次更新了一下，重启就会一直报Integer cannot be cast to java.lang.String，死活起不来，在eclipse里调试确正常，不知道其他人有没有碰到过这个问题， 没办法，我只能在自己的版本中改为String.valueOf，应该改为String.valueOf更好一点吧

String强转换报ClassCastException

---

src/main/java/org/opencloudb/handler/ReloadHandler.java
src/main/java/org/opencloudb/handler/ShowHandler.java
src/main/java/org/opencloudb/parser/ManagerParseReload.java
src/main/java/org/opencloudb/parser/ManagerParseShow.java
src/main/java/org/opencloudb/response/ReloadQueryCf.java
src/main/java/org/opencloudb/response/ShowSQL.java
src/main/java/org/opencloudb/response/ShowSQLCondition.java
src/main/java/org/opencloudb/response/ShowSQLHigh.java
src/main/java/org/opencloudb/stat/HighFrequencySqlAnalyzer.java
src/main/java/org/opencloudb/stat/HostStatAnalyzer.java
src/main/java/org/opencloudb/stat/QueryConditionAnalyzer.java
src/main/java/org/opencloudb/stat/QueryResultDispatcher.java
src/main/java/org/opencloudb/stat/TableStat.java

支持设置规则 reload @@query_cf=表名&字段  
支持清除规则 reload @@query_cf=NULL
支持 show @@sql.condition

增加 SQL 条件的分析，用于 列值/访问次数  的实时统计

---

src/main/java/io/mycat/MycatServer.java
src/main/java/io/mycat/route/function/PartitionByPattern.java
src/main/java/io/mycat/route/parser/druid/impl/DruidSelectParser.java
src/main/java/io/mycat/server/config/loader/ConfigFactory.java
src/main/java/io/mycat/server/config/loader/LocalLoader.java
src/main/java/io/mycat/server/sequence/SequenceHandler.java
src/main/java/io/mycat/util/rehasher/HashType.java
src/test/java/io/mycat/SimpleCachePool.java
src/test/java/io/mycat/backend/postgresql/EchoServer.java
src/test/java/io/mycat/backend/postgresql/PostgresqlKnightriders.java

This pull request is focused on resolving occurrences of Sonar rule squid:EmptyStatementUsageCheck - Empty statements should be removed
You can find more information about the issue here:
https://dev.eclipse.org/sonar/coding_rules#q=squid:EmptyStatementUsageCheck
Please let me know if you have any questions.
Kirill Vlasov

Empty statements should be removed

---

src/main/java/demo/catlets/ShareJoin.java
src/main/java/io/mycat/backend/heartbeat/MySQLDetector.java
src/main/java/io/mycat/net/Connection.java
src/main/java/io/mycat/route/handler/HintHandlerFactory.java
src/main/java/io/mycat/server/interceptor/impl/DefaultSqlInterceptor.java
src/main/java/io/mycat/sqlengine/sharejoin/TableFilter.java

share join时，比如：
/*!mycat:catlet=demo.catlets.ShareJoin*/ 
select a.id as aid, b.id as bid, b.name as tit from customer a,company b where a.company_id=b.id 
会报错：close connection,reason:program err:java.lang.IndexOutOfBoundsException:
// 原因是左表的select列没有包含 join 列，在获取结果时报上没的错误
修复就是给他加上join列：
/*!mycat:catlet=demo.catlets.ShareJoin*/ 
select a.id as aid,company_id, b.id as bid, b.name as tit from customer a,company b where a.company_id=b.id 
这样就不会报错了。

fix sharejoin bug

---

src/main/java/org/opencloudb/route/RouteService.java
src/main/java/org/opencloudb/route/handler/HintSQLHandler.java
src/main/java/org/opencloudb/route/impl/AbstractRouteStrategy.java

rt
例如:/*!mycat: sql=select * from ttt where ttt='26246'*/INSERT INTO ttt
由于sqlType用的是Insert的type(4),会导致报出数组越界的错误

修复 注解SQL的 sqlType 与 实际SQL的 sqlType 不一致问题

---

src/main/java/org/opencloudb/interceptor/impl/DefaultSqlInterceptor.java
src/test/java/org/opencloudb/parser/TestEscapeProcess.java

之前的修正有问题，Pattern为普通字符模式结果修成了正则，但依然应该无法解决sql中边界符单引号的区分问题，可能导致sql破坏。
虽然逻辑目前已不用但代码仍然存在的情况下改为了字符串遍历，另外修复了测试的bug

fix the quote bug in DefaultSqlInterceptor

---

src/main/java/org/opencloudb/mpp/DataMergeService.java
src/main/java/org/opencloudb/mysql/nio/handler/MultiNodeHandler.java
src/main/java/org/opencloudb/mysql/nio/handler/MultiNodeQueryHandler.java

1. Mycat sql time and hang problem.
As 1.5 problem.
2. SQL error and tx rollback blocked in client.
客户端在SQL出错后回滚时被卡住
----------------------------------------------------------------------------------------------------------------------------
例1-1
mysql> begin;
Query OK, 0 rows affected (0.00 sec)
mysql> select id, count(username) from travelrecord group by username order by id;
ERROR 1105 (HY000): java.lang.IllegalArgumentException: all columns in group by clause should be in the selected column list.!username
mysql> select id, username, count(username) from travelrecord group by username order by id;
ERROR 1003 (HY000): Transaction error, need to rollback.java.lang.IllegalArgumentException: all columns in group by clause should be in the selected column list.!username
mysql> rollback; …

Fixbug: 1. Mycat-1.4 hang problem 2. if query error then rollback blocked problem 3. MySQL backend connection error and Mycat responses OK

---

src/main/java/org/opencloudb/mysql/nio/handler/MultiNodeHandler.java
src/main/java/org/opencloudb/mysql/nio/handler/MultiNodeQueryHandler.java

一、客户端在SQL出错后回滚时被卡住(Mycat-1.4、1.5)
----------------------------------------------------------------------------------------------------------------------------
例1-1
mysql> begin;
Query OK, 0 rows affected (0.00 sec)
mysql> select id, count(username) from travelrecord group by username order by id;
ERROR 1105 (HY000): java.lang.IllegalArgumentException: all columns in group by clause should be in the selected column list.!username
mysql> select id, username, count(username) from travelrecord group by username order by id;
ERROR 1003 (HY000): Transaction error, need to rollback.java.lang.IllegalArgumentException: all columns in group by clause should be in the selected column list.!username
mysql> rollback;
例1-2
mysql> begin;
Query OK, 0 rows affected (0.00 sec)
mysql> select id, …

Fixbug: 1. SQL error and tx rollback blocked in client. 2. MySQL backend connection error and Mycat response OK

---

src/main/java/org/opencloudb/route/function/PartitionByMonth.java
src/main/java/org/opencloudb/route/util/RouterUtil.java
src/test/java/org/opencloudb/route/function/PartitionByMonthTest.java

代码改动
=======
1. 按月分片设置起始月份范围从而循环使用，对落在此范围外的数据通过计算偏移得到目标分片
2. 通过分片规则计算出节点值后检查节点值是否在对应的table合理的data node区间，如果计算出的
节点值没有对应的data node节点，则打印一条错误信息
单元测试
=======
1. 按月循环分片
测试四个分片，分片日期从2016年5月到2016年8月，日期格式为 20160501 和 2016-05-01
测试日期范围从2014年1月到2017年12月
2. 没有对应data node节点的情况
这里只测试了原始的按月分片情况下， 分片日期从2016年5月开始
MySQL [TESTDB]> explain insert into test4ptn_date2(id, date) values (1, '2016-09-22');
ERROR 1064 (HY000): Can't find a valid data node for specified node index :TEST4PTN_DATE2 -> DATE -> 2016-09-22 -> Index : 4
MySQL [TESTDB]> explain insert into test4ptn_date2(id, date) values (1, '2015-09-22');
ERROR 1064 (HY000): Can't find a valid data node for specified node index :TEST4PTN_DATE2 -> DATE -> 2015-09-22 -> Index: -8
之前遇到这种情况，mycat直接抛出 java.lang.IndexOutOfBoundsException: Index: 7, Size: 7 …

按月分片添加结束日期（月份）从而循环使用分片

---

src/main/java/io/mycat/server/ServerConnection.java
src/main/java/io/mycat/server/handler/MysqlInformationSchemaHandler.java
src/main/java/io/mycat/server/handler/SetHandler.java
src/main/java/io/mycat/server/util/SchemaUtil.java

rt
1、 SET NAMES 'utf8' COLLATE 'utf8_general_ci' 错误处理
2、	兼容PhpAdmin's 控制台管理, 为此支持对MySQL元数据的模拟返回，现在达到可用状态

1.6 	兼容PhpAdmin's 控制台管理, 为此支持对MySQL元数据的模拟返回，现在达到可用状态

---

src/main/java/demo/catlets/BatchInsertSequence.java
src/main/java/io/mycat/config/ConfigInitializer.java
src/main/java/io/mycat/config/model/SystemConfig.java
src/main/java/io/mycat/route/parser/ManagerParseShow.java
src/main/java/io/mycat/route/parser/druid/DruidSequenceHandler.java
src/main/java/io/mycat/route/sequence/handler/DistributedSequenceHandler.java
src/main/java/io/mycat/route/sequence/handler/IncrSequenceZKHandler.java
src/test/java/io/mycat/sequence/DistributedSequenceHandlerTest.java
src/test/java/io/mycat/sequence/IncrSequenceZKHandlerTest.java

1. 改善两种基于ZK的全局ID生成算法单元测试
2. 在MyCat载入配置中正式加入两种基于ZK的全局ID生成算法，配置如下
```
<system>
<property name="sequnceHandlerType">3</property>
</system>
<system>
<property name="sequnceHandlerType">4</property>
</system>
```

1. 改善两种基于ZK的全局ID生成算法单元测试2. 在MyCat载入配置中正式加入两种基于ZK的全局ID生成算法

---

src/main/assembly/bin/dataMigrate.sh
src/main/java/io/mycat/util/dataMigrator/ConfigComparer.java
src/main/java/io/mycat/util/dataMigrator/DataClearRunner.java
src/main/java/io/mycat/util/dataMigrator/DataIO.java
src/main/java/io/mycat/util/dataMigrator/DataIOFactory.java
src/main/java/io/mycat/util/dataMigrator/DataMigrateRunner.java
src/main/java/io/mycat/util/dataMigrator/DataMigrator.java
src/main/java/io/mycat/util/dataMigrator/DataMigratorArgs.java
src/main/java/io/mycat/util/dataMigrator/DataMigratorUtil.java
src/main/java/io/mycat/util/dataMigrator/DataNode.java
src/main/java/io/mycat/util/dataMigrator/DataNodeClearGroup.java
src/main/java/io/mycat/util/dataMigrator/DataNodeMigrateInfo.java
src/main/java/io/mycat/util/dataMigrator/MigratorConditonFilesMaker.java
src/main/java/io/mycat/util/dataMigrator/TableMigrateInfo.java
src/main/java/io/mycat/util/dataMigrator/dataIOImpl/MysqlDataIO.java
src/main/java/io/mycat/util/exception/DataMigratorException.java
src/main/resources/migrateTables.properties

**原理：**读取要迁移的节点数据表拆分字段值，根据迁移后的配置进行路由，将需要迁移的数据id字段值记录在文件中，然后通过mysqldump将id字段值所有数据dump到sql文件中，再将sql文件导入到迁移后的节点上，最后将要迁移的节点数据上已迁移的数据删除。
一个拆分表数据的迁移过程：
{
old dn1->重新路由->中间文件->导出数据->导入数据->new dn1
old dn2->重新路由->中间文件->导出数据->导入数据->new dn2
...
}
异常处理：（一个拆分表数据迁移出错，不影响其他拆分表的迁移，拆分表迁移过程中任何环节出错，停止整个拆分表的迁移任务，迁移程序执行完成后，提供迁移成功和失败拆分表信息列表，及失败原因，维护人员根据失败原因进行故障排查后，重新迁移失败的拆分表）
读取配置文件->抛出错误，终止程序
生成中间文件，数据导出，导入->抛出错误，终止出错节点所属拆分表的所有节点线程任务，不影响其他拆分表线程任务
**扩容缩容步骤：**
1、复制schema.xml、rule.xml并重命名为newSchema.xml、newRule.xml放于conf目录下
2、修改newSchema.xml和newRule.xml配置文件为扩容缩容后的mycat配置参数（表的节点数、数据源、路由规则）
3、修改conf目录下的migrateTables.properties配置文件，告诉工具哪些表需要进行扩容或缩容,没有出现在此配置文件的schema表不会进行数据迁移
4、修改bin目录下的dataMigrate.sh脚本文件，具体参数含义参考bin/dataMigrate.sh中的注释
5、停止mycat服务（如果可以确保扩容缩容过程中只有读操作，也可以不停止mycat服务）
6、执行bin/ dataMigrate.sh脚本，开始扩容/缩容过程 …

mycat1.6 自动化扩容缩容工具，支持任意路由规则

---

src/main/java/io/mycat/backend/datasource/PhysicalDBNode.java
src/main/java/io/mycat/route/RouteService.java
src/main/java/io/mycat/route/handler/HintHandlerFactory.java
src/main/java/io/mycat/server/parser/ServerParse.java

注解支持的'#'不被mybatis兼容
添加hint sql支持的格式/** mycat: */
2、修改当事务提交模式为手动提交场景下，如果指定db_type=slave会强制走从节点的问题，原则是在事务内无论是否指定注解都应该走主节点。

增加支持/**mycat:*/注释注解头

---

src/main/java/io/mycat/MycatServer.java
src/main/java/io/mycat/buffer/BufferArray.java
src/main/java/io/mycat/buffer/BufferPool.java
src/main/java/io/mycat/buffer/ByteBufferArena.java
src/main/java/io/mycat/buffer/DirectByteBufferPool.java
src/main/java/io/mycat/config/model/SystemConfig.java
src/main/java/io/mycat/manager/response/ShowProcessor.java
src/main/java/io/mycat/net/NIOProcessor.java
src/main/java/io/mycat/route/impl/DruidMycatRouteStrategy.java
src/main/java/io/mycat/route/util/RouterUtil.java
src/test/java/io/mycat/buffer/TestByteBufferArena.java

初步测试结果：
**DirectByteBufferPool吞吐量：**
第一次测试：
第二次测试：
第三次测试：
第四次测试：
第五次测试：
**ByteBufferArena吞吐量：**
第一次测试：
第二次测试：
第三次测试：
第四次测试：
第五次测试：

将缓冲池抽象化为接口BufferPool，并且让ByteBufferArena和DirectByteBufferPool实现它。将MyCat的缓冲池修改为BufferPool类型，实现还是DirectByteBufferPool。（测试ByteBufferArena中）

---

src/main/java/org/opencloudb/config/Versions.java
src/main/java/org/opencloudb/config/Versions.template
src/main/java/org/opencloudb/config/loader/xml/XMLServerLoader.java
src/main/java/org/opencloudb/config/model/SystemConfig.java
src/main/java/org/opencloudb/net/FrontendConnection.java
src/main/java/org/opencloudb/response/ShowVersion.java
src/main/java/org/opencloudb/server/response/SelectVersion.java

server.xml的 system下，添加 fakeMySQLVersion 设置项，用来设置mycat与客户端交互时伪装的MySQL的具体版本，之前一直是5.5.8，这对于后端mysql版本较新时，使用mycat会丢失一些新特性。
代码的修改思路就是把之前的接口Versions改为抽象类，在load server.xml的时候，可以根据fakeMySQLVersion的值来配置SERVER_VERSION，如果没有设置fakeMySQLVersion，则使用默认值。
测试
在server.xml中，添加
<system>
...
<property name="fakeMySQLVersion">5.6.3</property>
...
</system>
下面是分别设置为 5.6.4， 5.6.3， 5.7.4， 5.5.8，不设置时候的输出
测试1 简单的select version
Server version: 5.6.4-mycat-1.5.1-RELEASE-20160524231026 MyCat Server (OpenCloundDB)
Copyright (c) 2000, 2015, Oracle, MariaDB Corporation Ab and others.
Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
MySQL [TESTDB]> select version();
+------------------------------------------+
| VERSION()                                | …

server.xml添加一个配置项用来设置mycat要模拟的mysql的版本

---

src/main/java/io/mycat/config/Versions.java
src/main/java/io/mycat/config/Versions.template
src/main/java/io/mycat/config/loader/xml/XMLServerLoader.java
src/main/java/io/mycat/config/model/SystemConfig.java
src/main/resources/server.xml

具体的改动参考下面，这里额外修改了server.xml，注释中添加了 fakeMySQLVersion的配置
https://github.com/MyCATApache/Mycat-Server/pull/916

(移植1.5branch上的pull request916) server.xml中添加配置项让mycat可以设置要模拟的mysql的版本号

---

src/main/java/io/mycat/route/util/RouterUtil.java

修复bug #938 当分库字段为uuid时，使用sharding-by-murmur规则配置主子表关系，导致主子表关联数据无法插入到同一个库中

修复bug #938 当分库字段为uuid时，使用sharding-by-murmur规则配置主子表关系，导致主子表关联数据无法插入到同一个库中 

---

src/main/java/org/opencloudb/handler/SelectHandler.java
src/main/java/org/opencloudb/parser/ManagerParseSelect.java
src/main/java/org/opencloudb/response/SelectTxReadOnly.java

具体修改请参考 pull request 942
https://github.com/MyCATApache/Mycat-Server/pull/942
有部分代码已经在https://github.com/MyCATApache/Mycat-Server/pull/930 中完成，
因此做部分的移植即可。
下面是测试结果， 在mycat-eye中也可以成功添加监控。
连接manager端口(9066)， mycat配置模拟MySQL的版本为 5.6.20
Server version: 5.6.20-mycat-1.5.1-RELEASE-20160614153228 MyCat Server (monitor)
Copyright (c) 2000, 2015, Oracle, MariaDB Corporation Ab and others.
Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
MySQL [(none)]> select @@session.tx_read_only;
+------------------------+
| @@session.tx_read_only |
+------------------------+
|                      0 |
+------------------------+
1 row in set (0.00 sec)
MySQL [(none)]> select @@tx_read_only;
ERROR 1003 (HY000): Unsupported statement
MySQL [(none)]> select @@global.tx_read_only;
ERROR …

Port pull request 942 from 1.6 to 1.5, manager端口支持select @@session.tx_read_only

---

src/main/resources/schema.dtd

微软Azure MySQL DB的用户名里面会包含一个%字符。由于当前的schema.dtd里面user配置是NMTOKEN，%是不允许的。

Allow % in user name, which is used in some cloud MySQL DB.

---

src/main/java/io/mycat/route/parser/druid/impl/DruidUpdateParser.java
src/main/java/io/mycat/util/StringUtil.java
src/test/java/io/mycat/parser/druid/DruidUpdateParserTest.java

update hotnews set id = 1 where name = 234;这个语句会报错，因为分片字段不能修改。
但是：update hotnews h set h.id = 1 where h.name = 234;加上别名的语句则不会报错并且能修改成功。
这是由于UpDate解析验证是否修改分片字段代码缺陷导致，没有考虑别名。作了修改并添加单元测试

修复UpDate解析验证是否修改分片字段代码缺陷导致，没有考虑别名

---

src/test/java/io/mycat/route/DDLRouteTest.java

测试语句中多了一个 DEFAULT，导致druid解析报错。同时
mysql支持下面的alter：
alter table COMPANY add column test3 varchar(255) null after name, CHARACTER SET DEFAULT;
，但是 druid 不支持，druid要求CHARACTER SET后面必须是等于号：
alter table COMPANY add column test3 varchar(255) null after name, CHARACTER SET = UTF8;

fix DDLRouteTest中测试的sql语句的语法问题

---

src/main/java/io/mycat/route/function/AbstractPartitionAlgorithm.java

异常出现的场景：
1.按日期分片，10天一个分片，10个分片节点
2.跨第一个分片和第十个分片查询时会出现 ERROR 1064 (HY000): NullPointerException
源代码分析：
/**
对于存储数据按顺序存放的字段做范围路由，可以使用这个函数
@param algorithm
@param beginValue
@param endValue
@return
*/
public static Integer[] calculateSequenceRange(AbstractPartitionAlgorithm algorithm, String beginValue, String endValue) {
Integer begin = 0, end = 0;
begin = algorithm.calculate(beginValue);
end = algorithm.calculate(endValue);
if(begin == null || end == null){
return new Integer[0];
}
if (end >= begin) { //该判断在以上场景时 end为0 begin为9 ，导致判断不通过返回了null
int len = end-begin+1;
Integer [] re = new Integer[len];
for(int i =0;i<len;i++){
re[i]=begin+i;
}
return re;
}else{
return null;
}
}

1.6版本-修复循环使用分片节点时，在跨头尾节点查询时出现的空指针异常

---

src/main/java/org/opencloudb/route/function/AbstractPartitionAlgorithm.java

异常出现的场景：
1.按日期分片，10天一个分片，10个分片节点
2.跨第一个分片和第十个分片查询时会出现 ERROR 1064 (HY000): NullPointerException
源代码分析：
/**
* 对于存储数据按顺序存放的字段做范围路由，可以使用这个函数
* @param algorithm
* @param beginValue
* @param endValue
* @return
*/
public static Integer[] calculateSequenceRange(AbstractPartitionAlgorithm algorithm, String beginValue, String endValue) {
Integer begin = 0, end = 0;
begin = algorithm.calculate(beginValue);
end = algorithm.calculate(endValue);
if(begin == null || end == null){
return new Integer[0];
}
if (end >= begin) {     //该判断在以上场景时   end为0   begin为9  ，导致判断不通过返回了null
int len = end-begin+1;
Integer [] re = new Integer[len];
for(int i =0;i<len;i++){
re[i]=begin+i;
}
return re;
}else{
return null;
}
}

1.5版本-修复循环使用分片节点时，在跨头尾节点查询时出现的空指针异常

---

src/main/java/io/mycat/config/model/SystemConfig.java
src/main/java/io/mycat/route/RouteResultsetNode.java
src/main/java/io/mycat/route/parser/druid/impl/DruidInsertParser.java
src/main/java/io/mycat/route/util/RouterUtil.java
src/main/java/io/mycat/server/NonBlockingSession.java
src/main/java/io/mycat/server/handler/Explain2Handler.java
src/main/java/io/mycat/server/handler/ServerLoadDataInfileHandler.java
src/main/java/io/mycat/server/interceptor/impl/GlobalTableUtil.java
src/main/resources/server.xml

**配置方法：**
在server.xml的system标签中添加：
`<property name="handleDistributedTransactions">0</property>`
值可以为0,1,2
0 - 不检查分布式事务，执行所有分布式事务
1 - 过滤掉所有分布式事务，不执行，直接报错
2 - 检查分布式事务，但执行，只是打日志
**实现说明：**
Nonblockingsession类处理事务还有请求，在这个类中过滤掉分布式事务。
一个地方是execute方法中，添加如果是更新语句（insert，update，delete），并且不是全局表更新，那么检查是否为分布式事务。
另一个地方是在commit方法中，做相似的检查。
举例：
如下两种分布式事务：
`1. insert into hotnews(id) values(1),(2);`
`2. set autocommit = 0;insert into hotnews(id) values(3),(4);commit;`
如果handleDistributedTransactions配置为0，则顺利执行。
如果handleDistributedTransactions配置为1，则：
对于事务1：
```
mysql>insert into hotnews(id) values(1),(2);
1148 - Distributed transaction is disabled!
```
对于事务2:
```
mysql> set autocommit = 0;
Query OK, 0 rows affected
mysql> insert into hotnews(id) values(3),(4);
Query OK, 2 rows affected
mysql> commit;
1148 - …
```

修改分布式事务校验开关

---

src/main/java/org/opencloudb/parser/druid/impl/DruidInsertParser.java
src/main/java/org/opencloudb/parser/druid/impl/DruidUpdateParser.java
src/test/java/org/opencloudb/parser/druid/DruidUpdateParserTest.java
src/test/java/org/opencloudb/route/DruidMysqlRouteStrategyTest.java

对于set和where子句中对于分片字段实际上并没有更新的update语句，允许执行而不抛出异常。修改一些相关的报错语句的内容，添加了针对新的处理逻辑的测试用例，比如update针对and，or，子查询等情况。
代码实现思路
--------------
遍历where子句的AST，寻找是否有与update子句中更新分片字段相同的条件，
o 如果发现有or或者xor，然后分片字段的条件在or或者xor中的，这种情况update也无法执行，比如
update mytab set ptn_col = val, col1 = val1 where col1 = val11 or ptn_col = val；
但是下面的这种update是可以执行的
update mytab set ptn_col = val, col1 = val1 where ptn_col = val and (col1 = val11 or col2 = val2);
o 如果没有发现与update子句中更新分片字段相同的条件，则update也无法执行，比如
update mytab set ptn_col = val， col1 = val1 where col1 = val11 and col2 = val22;
o 如果条件之间都是and，且有与更新分片字段相同的条件，这种情况是允许执行的。比如
update mytab set ptn_col = val, col1 = val1 where ptn_col = val and col1 = val11 and col2 = val2;
o 对于一些特殊的运算符，比如between，not，或者子查询，遇到这些子句现在不会去检查分片字段是否在此类子句中，
即使分片字段在此类子句中，现在也认为对应的update语句无法执行。 …

修改对于update语句中set子句包含分片字段更新语句的处理逻辑

---

src/main/java/org/opencloudb/route/function/PartitionByDate.java

旧代码逻辑会照成以下问题
假设现在有3个分片，按1天一个分片，node值分别为0、1、2
2016-01-01----node0
2016-01-02----node1
2016-01-03----node2
2016-01-04----node0
2016-01-05----node1
2016-01-06----node2
2016-01-07----node0
2016-01-08----node1
2016-01-09----node2
第一种情况
查询2016-01-03至2016-01-04时，之前的代码会出现空指针异常（已修复）
第二种情况
查询2016-01-02至2016-01-05时，只会发送node1执行，略过了node2和node0
第三种情况
查询2016-01-01至2016-01-08时，只会发送到node0和node1，本应发送所有节点
现代码调整为计算日期区间内的所有日期，不再只根据开始时间和结束时间计算路由

按天分片，跨头尾分片BUG修改

---

src/main/java/org/opencloudb/route/util/RouterUtil.java

此项我看到1.6已做修改 bug#938
修改
processERChildTable函数
//String joinKeyVal = insertStmt.getValues().getValues().get(joinKeyIndex).toString();
改为如下：
String joinKeyVal = StringUtil.removeBackquote(insertStmt.getValues().getValues().get(joinKeyIndex).toString());

ER分片是子表插入时，获取joinkey字段时，其数据前后有引号导致hash算出来的分片错误

---

src/main/java/org/opencloudb/parser/druid/impl/DefaultDruidParser.java

bug：查询分片表时出现未根据片键路由
SQL：SELECT * FROM `shard_table` WHERE shard_field=100;
原因：表名上存在【`】符号
解决：
函数buildRouteCalculateUnits中的
if(visitor.getAliasMap() != null && visitor.getAliasMap().get(condition.getColumn().getTable().toUpperCase()) == null) {//子查询的别名条件忽略掉,不参数路由计算，否则后面找不到表
此判断后面部分在查询的SQL中如果表名存在【`】符号的话其表达式值为true，这样就进入了continue，导致在查询时无法进行路径进行了全片扫描。
修改如下，增加去【`】符号方法
if(visitor.getAliasMap() != null && visitor.getAliasMap().get(StringUtil.removeBackquote(condition.getColumn().getTable().toUpperCase())) == null) {//子查询的别名条件忽略掉,不参数路由计算，否则后面找不到表

查询语句表名中存在【`】符号时无法路由至对应分片

---

src/main/java/io/mycat/backend/mysql/nio/handler/SingleNodeHandler.java
src/main/java/io/mycat/net/mysql/BinaryRowDataPacket.java
src/test/java/io/mycat/sqlexecute/ServerPrepareTest.java

出现异常的原因在于SingleNodeHandler处理prepare结果包不能直接输出,应该等待fieldEofResponse方法的包发出去以后才能发
TODO : 多节点结果返回(MultiNodeQueryHandler)在server.xml打开useOffHeapForMerge = 1配置以后也无法收到正确的数据, 需要根据新的实现进行适配

fixed : 修复mycat预处理单节点返回结果异常的bug

---

src/main/java/io/mycat/backend/mysql/nio/handler/MultiNodeQueryHandler.java
src/main/java/io/mycat/net/mysql/BinaryRowDataPacket.java

当`server.xml`里面配置`useOffHeapForMerge = 1`时,使用新的内存管理方式保存数据，以及新的方式写数据到前端，预处理需要适配新的内存管理方式来返回正确的数据。
more : 
1. 重构了`BinaryRowDataPacket.java`相关代码
2. 代码调整 : `MultiNodeQueryHandler.java`两个`outputMergeResult`方法if条件移到for循环和while循环外面

fixed : 修复mycat预处理多节点在useOffHeapForMerge = 1配置下返回结果异常的bug

---

src/main/java/io/mycat/MycatServer.java
src/main/java/io/mycat/backend/ConMap.java
src/main/java/io/mycat/backend/datasource/PhysicalDBPool.java
src/main/java/io/mycat/backend/datasource/PhysicalDatasource.java
src/main/java/io/mycat/backend/jdbc/JDBCDatasource.java
src/main/java/io/mycat/backend/mysql/nio/MySQLDataSource.java
src/main/java/io/mycat/backend/postgresql/PostgreSQLDataSource.java
src/main/java/io/mycat/config/ConfigInitializer.java
src/main/java/io/mycat/config/MycatConfig.java
src/main/java/io/mycat/manager/handler/ShowHandler.java
src/main/java/io/mycat/manager/response/ReloadConfig.java
src/main/java/io/mycat/manager/response/ShowBackend.java
src/main/java/io/mycat/manager/response/ShowBackendOld.java
src/main/java/io/mycat/net/NIOProcessor.java
src/main/java/io/mycat/route/parser/ManagerParseShow.java

1、前置config 增强的自检功能，含socket链路的交互检查
2、高并发下， 偶尔（测试的时候，连续多次reload，肯定会有一次出现） reload @@config_all 后 getConnectionHandler 阻塞，耗时1分钟 极易引发整体服务问题，
3、最后一个步骤， old datasource 不强杀，基本不丢事务 
//-------------------------------------------------------
整个reload 过程，大致如下：
1、载入新的配置， ConfigInitializer 内部完成自检工作
2、承接
2.1、老的 dataSource 继续承接新建请求
2.2、新的 dataSource 开始初始化， 完毕后交由 2.3
2.3、新的 dataSource 开始承接新建请求
2.4、老的 dataSource 内部的事务执行完毕， 相继关闭
2.5、老的 dataSource 超过阀值的，强制关闭

reload @@config/@@config_all 功能增强, 真正实现热更新

---

src/test/java/io/mycat/route/function/RuleFunctionSuitTableTest.java
src/test/resources/autopartition-long2.txt
src/test/resources/route/rule.xml
src/test/resources/route/schema.xml

增加了分片表规则一致性校验而导致部分单元测试测试失败，修复这些单元测试使其能够通过测试

修复部分单元测试因增加分片表规则一致性校验而出错的问题

---

src/main/java/io/mycat/backend/jdbc/JDBCConnection.java

此异常会导致JDBCConection不释放，最终 sql timeout

修复NullPointerException异常

---

src/main/java/io/mycat/backend/mysql/nio/handler/MultiNodeQueryHandler.java

MultiNodeQueryHandler的fieldPackets数组在遇到avg函数会多存储AVG[i]COUNT这一列,当遇到这种情况,需要从fieldPackets中去除这个列

修复MultiNodeQueryHandler fieldPackets多余列存储问题

---

src/main/java/io/mycat/config/Capabilities.java
src/main/java/io/mycat/config/model/SystemConfig.java
src/main/java/io/mycat/net/FrontendConnection.java
src/main/java/io/mycat/net/mysql/HandshakeV10Packet.java
src/main/resources/server.xml
src/test/java/io/mycat/sqlexecute/MycatMulitJdbcVersionTest.java

针对issue #1092
新增HandshakeV10Packet用于解决高版本jdbc驱动连接mycat抛如下异常:
```bash
com.mysql.cj.core.exceptions.UnableToConnectException: CLIENT_PLUGIN_AUTH is required
```
PS: 在`server.xml`里面新增useHandshakeV10配置参数，当useHandshakeV10  = 1 表示启用HandshakeV10Packet来跟client通讯，如果useHandshakeV10 = 0，仍然用老的HandshakePacket跟client通讯。这么做主要考虑有BUG的情况可以屏蔽这部分功能。后期使用稳定可以直接使用HandshakeV10Packet进行处理

feature #1203 兼容高版本mysql jdbc连接mycat

---

src/main/java/io/mycat/sqlengine/mpp/UnsafeRowGrouper.java

在UnsafeRowGrouper的getGroupKey方法中，对decimal列的处理逻辑上出现问题(索引下标用错)导致聚合的结果出错，修复这个bug

修复新内存模式decimal列进行聚合的bug

---

src/main/java/io/mycat/server/handler/ServerPrepareHandler.java

针对#1248:
`ServerPrepareHandler`中`prepareStmtBindValue`方法对于替换占位符的逻辑处理有问题, 改写处理逻辑, 并支持特殊字符的处理

修复预处理sql字符串类型字段带转义字符处理异常的bug

---

src/main/java/io/mycat/server/ServerConnection.java

navicat 11.2.13中生成的sql部分有个0
```
CONCAT(ROUND(SUM(DURATION)/0*100,3), '%') AS 
```
所以
```
sql.contains("CONCAT(ROUND(SUM(DURATION)/") 
```
就可以了,否则还是err 1064

fix navicat INFORMATION_SCHEMA.PROFILING

---

src/main/java/org/opencloudb/route/impl/DruidMycatRouteStrategy.java

Mycat对于select @@语句的判断逻辑如下（DruidMycatRouteStrategy类的routeSystemInfo方法）：
case ServerParse.SELECT://if origSQL is like select @@
if(stmt.contains("@@")){
return analyseDoubleAtSgin(schema, rrs, stmt);
}
如果一个查询中包含@@，如:
> select * from tt_table where id = "aabb@@ccdd";
也会按照select @@的判断逻辑处理，导致路由结果有误

修复Mycat处理select @@语句的漏洞

---

src/main/java/io/mycat/net/mysql/ExecutePacket.java

PHP5.3和5.4版本通过PDO使用服务端预处理连接mycat抛ArrayIndexOutOfBoundsException异常，原因在于低版本的PDO对mysql `COM_STMT_EXECUTE`协议的实现与mysql官方实现存在歧义。对`ExecutePacket`类的读取方式做修改以兼容低版本的PHP PDO
**低版本(5.3和5.4可以测出来)的PHP PDO出现BUG原因分析:**
mysql协议COM_STMT_EXECUTE: [https://dev.mysql.com/doc/internals/en/com-stmt-execute.html](https://dev.mysql.com/doc/internals/en/com-stmt-execute.html)
```
COM_STMT_EXECUTE
execute a prepared statement
direction: client -> server
response: COM_STMT_EXECUTE Response
payload:
1              [17] COM_STMT_EXECUTE
4              stmt-id
1              flags
4              iteration-count
if num-params > 0:
n              NULL-bitmap, length: (num-params+7)/8
1              new-params-bound-flag
if new-params-bound-flag == 1:
n              type of each parameter, length: num-params * 2
n …
```

fix #1278 修复PHP5.3,5.4版本PDO使用服务端prepare的BUG

---

src/main/java/io/mycat/server/parser/ServerParseSet.java
src/test/java/io/mycat/parser/ServerParserTest.java

`set xa = on`
（ **=** 后面有空格，Tab或换行键）语句会解析错误

完善set xa=on语句的解析逻辑，修复之前的bug

---

src/main/java/io/mycat/backend/mysql/BindValueUtil.java
src/main/java/io/mycat/backend/mysql/MySQLMessage.java

mycat预处理实现中，对于空串会识别为`NULL`，修复这个BUG

fix #1294 修复预处理将空串识别为NULL的BUG

---

src/main/java/io/mycat/util/ByteUtil.java

io.mycat.util.ByteUtil中getShort()方法获取short方式有误,
影响mycat预处理对smallint类型的转换, 修改getShort方法, 修复这个BUG

fix #1308 修复mycat预处理对smallint类型转换出错的BUG

---

src/main/java/io/mycat/config/Versions.java
src/main/java/io/mycat/server/NonBlockingSession.java

1.Java高编译低运行错误(ConcurrentHashMap.keySet)，如果jdk1.8编译mycat,用jdk1.7去执行则会出现java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.keySet() 
Ljava/util/concurrent/ConcurrentHashMap$KeySetView;错误，改为noblockingsession类统一使用concurrentMap接口，避免出现jdk版本不一致导致的错误。
2.服务器上version.java中文字是乱码，改为中文

解决Java高编译低运行错误(ConcurrentHashMap.keySet)

---

src/main/java/io/mycat/backend/mysql/nio/handler/MiddlerQueryResultHandler.java
src/main/java/io/mycat/backend/mysql/nio/handler/MultiNodeQueryHandler.java
src/main/java/io/mycat/route/RouteService.java
src/main/java/io/mycat/route/impl/DruidMycatRouteStrategy.java
src/main/java/io/mycat/route/parser/druid/MycatSchemaStatVisitor.java
src/test/java/io/mycat/route/TestSelectBetweenSqlParser.java

1. 修复 存在sql 改写的情况下,路由缓存可能缓存的结果不对的问题. 
思路为,如果sql 需要改写,或拆分,不直接做缓存.缓存拆分后的sql.
2. 修复 存在子查询，并且子查询先执行的情况下,如果子查询没有返回结果.报空指针的问题.
3. 如果子查询为 =some,=any,=all  不改写sql时,走直接路由的方式.

修复 存在sql 改写的情况下,路由缓存可能缓存的结果不对的问题.  

---

src/main/java/io/mycat/buffer/DirectByteBufferPool.java

报错信息：
wrapper.log里会出现：
java.lang.ArrayIndexOutOfBoundsException: -158
at io.mycat.buffer.DirectByteBufferPool.allocateBuffer(DirectByteBufferPool.java:122) ~[Mycat-server-1.6.5-DEV.jar:?]
at io.mycat.buffer.DirectByteBufferPool.allocate(DirectByteBufferPool.java:74) ~[Mycat-server-1.6.5-DEV.jar:?]
at io.mycat.net.AbstractConnection.setProcessor(AbstractConnection.java:212) ~[Mycat-server-1.6.5-DEV.jar:?]
at io.mycat.net.FrontendConnection.setProcessor(FrontendConnection.java:130) ~[Mycat-server-1.6.5-DEV.jar:?]
at io.mycat.net.NIOAcceptor.accept(NIOAcceptor.java:116) ~[Mycat-server-1.6.5-DEV.jar:?]
at io.mycat.net.NIOAcceptor.run(NIOAcceptor.java:92) ~[Mycat-server-1.6.5-DEV.jar:?]

修复了DirectByteBufferPool.java里int类型内存变量越界问题

---

src/main/assembly/bin/init_zk_data.sh

1. [修改] $JAVA_HOME判断逻辑有缺陷，改为直接尝试运行搜索路径下的java是否成功
2. [新增] java搜索路径增加为：$MYCAT/conf/wrapper.conf里的wrapper.java.command -> $JAVA_HOME/bin/java -> $PATH/java
3. [修改] $MYCAT_HOME路径不在以用户当前所处目录为基准，而以init_zk_data.sh脚本的所在目录的父目录作为基准
4. [新增] 无论用户所处当前目录在哪儿，init_zk_data.sh均可以安全调用了

Update init_zk_data.sh with smarter JAVA and $MYCAT_HOME searching

---

src/main/java/io/mycat/backend/mysql/nio/MySQLConnection.java
src/main/java/io/mycat/backend/mysql/nio/handler/CommitNodeHandler.java
src/main/java/io/mycat/backend/mysql/nio/handler/MultiNodeCoordinator.java
src/main/java/io/mycat/backend/mysql/nio/handler/RollbackNodeHandler.java
src/main/java/io/mycat/backend/postgresql/PostgreSQLBackendConnection.java

改进思路如下：
增加从事务id的概念
从事务id= 事务id+库名.
mycat 通过事务id 控制全局事务.
借助
XA {START|BEGIN} xid: gtrid [, bqual [, formatID ]] 的 bqual 实现.
2. 修复 没有处理 xa start  xid 响应报文的问题.
可能导致 insert  影响行数不准确的问题.

修复,XA事务 涉及到一个mysql实例中多个数据库时,执行报错的问题.

---

src/main/java/io/mycat/MycatServer.java
src/main/java/io/mycat/route/MyCATSequnceProcessor.java
src/main/java/io/mycat/route/impl/DruidMycatRouteStrategy.java
src/main/java/io/mycat/route/impl/middlerResultStrategy/BinaryOpResultHandler.java
src/main/java/io/mycat/route/impl/middlerResultStrategy/InSubQueryResultHandler.java
src/main/java/io/mycat/route/impl/middlerResultStrategy/RouteMiddlerReaultHandler.java
src/main/java/io/mycat/route/impl/middlerResultStrategy/SQLAllResultHandler.java
src/main/java/io/mycat/route/impl/middlerResultStrategy/SQLExistsResultHandler.java
src/main/java/io/mycat/route/impl/middlerResultStrategy/SQLQueryResultHandler.java
src/main/java/io/mycat/route/parser/druid/DruidSequenceHandler.java
src/main/java/io/mycat/route/parser/druid/MycatSchemaStatVisitor.java
src/main/java/io/mycat/route/parser/druid/MycatSubQueryVisitor.java
src/main/java/io/mycat/route/parser/druid/impl/DefaultDruidParser.java
src/main/java/io/mycat/route/util/RouterUtil.java

1. 对于 EXISTS/NOT EXISTS, 判断subquery结果集是否为空即可.
2. 对于 = all 的子查询, 改写为 id = 1 and id = 2 .....
3. 增加对 两个表分片规则和节点都一样，关联字段是分片字段 情况下的子查询的支持.
4.批量插入使用自动生成主键方式时,影响行数不正确.偶尔返回给客户端多个OK报文. 导致客户端显示异常的问题。
5.批量插入显式指定mycat序列方式时,生成重复主键问题。
6. 优化 mycat 获取序列号锁粒度。优化思路为 mycat 批量插入获取序列号时,交给 BusinessExecutor 去处理. 在获取序列号时,每个表一把锁。通过降低锁粒度的方式 提高并发。类似于分段锁的概念。
优化后,如果是DB 方式,可以给 mycat_sequence name 列.加上索引 进一步提高并发.

子查询完善.及批量插入问题修复

---

src/main/java/io/mycat/backend/datasource/PhysicalDatasource.java

https://github.com/MyCATApache/Mycat-Server/issues/1524
BUG分析：
在从连接池中获取不到连接后，会判断当前池中的活跃连接数是否超过允许的最大连接数，如果没有超过则创建一个新的连接，这个过程在多线程环境下存在明显的问题，导致会创建超过配置的最大连接数。
修复思路：
1、引入锁保护连接池中已存在的连接，活跃连接。
2、引入一个超时机制，如果连接池的连接数已达到最大连接数后，有在获取连接的地方等待一段时间（目前默认为30s）,如果30S后还是没有可用连接，将报超过最大连接数。
是否写单元测试： 无
测试措施：
代码修复后，运行mycat服务器，然后写了一个查询案例：代码地址：http://git.oschina.net/zhcsoft/StudyDemo,测试URL:/StudyDemo/demo/testSelectOrder.do?uid=8A5EA76282C644A18267C07E8BC380F0,对该接口进行压力测试，让mycat连接不断创建，然后空闲后关闭连接，整个过程未见异常。

修复mycat连接数超出配置的maxCons属性bug

---

src/main/java/io/mycat/route/util/RouterUtil.java

修复没有主键批量insert 语句 中带有特殊字符 ( 时, 相应的列被改写的问题
例如
insert into sbtest1(c,k)values('ctest','()ktest'),('test2','test2'); 被改写成  insert into sbtest1(id,c,k)values(1,'ctest','(2)ktest'),(3,'test2','test2');

修复没有主键批量insert 语句 中带有特殊字符 ( 时, 相应的列被改写的问题

---

src/main/java/io/mycat/backend/jdbc/JDBCDatasource.java

新增sqlserver开源驱动jtds(net.sourceforge.jtds.jdbc.Driver)，可以使mycat完美支持sqlserver存储过程，解决使用官方驱动调用某些存储错误问题，如存储过程中入参为用户定义表类型(CREATE TYPE)可以有很好的支持。

使用sqlserver开源驱动jtds可以使mycat完美支持sqlserver存储过程，解决使用官方驱动存储调用错误问题

---

src/main/java/io/mycat/sqlengine/mpp/DataNodeMergeManager.java
src/main/java/io/mycat/sqlengine/mpp/RowDataPacketGrouper.java

例如: select id,count(k) from sbtest3;
如果 sbtest3 是分片表, 其中一个分片没有数据，在这种情况下 id列 有可能显示 null 值。

修复存在多个节点结果集汇聚的情况下。查询列可能为null的问题。

---

src/main/java/io/mycat/config/MycatPrivileges.java

com.alibaba.druid.sql.parser.ParserException: syntax error, error in
:'begin',expect END, actual EOF begin

修复 druid 不支持begin 语句的解析

---

src/main/java/io/mycat/backend/ConQueue.java
src/main/java/io/mycat/backend/datasource/PhysicalDatasource.java

本次出现会造成大量后端连接异常原因分析：
测试场景：数据库允许最大连接数为5，maxCon配置为10，可重现BUG
原因分析：由于connectionError与createNewConnection没有成对调用，导致totalConnection出现负数（自身引入bug）、二是因为mycat对应同一个连接，takeConn与returnConn没有成对被调用，导致activeCount出现负数，在这样的情况下，mycat一直向后端创建连接，但创建失败。

修复issues1524

---

src/main/java/io/mycat/net/AbstractConnection.java

详见issue#1616: https://github.com/MyCATApache/Mycat-Server/issues/1616

修复因前端连接register失败导致bytebuffer泄露的bug

---

src/main/java/io/mycat/route/parser/druid/impl/DruidSelectParser.java

我们的schema.xml如下：
<?xml version="1.0"?>
<!DOCTYPE mycat:schema SYSTEM "schema.dtd">
<mycat:schema xmlns:mycat="http://io.mycat/">
<schema name="snaker_test2" checkSQLschema="false" sqlMaxLimit="100">
<table name="wf_hist_order" subTables="wf_hist_order$1-3" dataNode="snakerNode" rule="sharding-by-month"/>
</schema>
<dataNode name="snakerNode" dataHost="snaker" database="snaker_test2"/>
<dataHost name="snaker" maxCon="1000" minCon="10" balance="0"
writeType="0" dbType="mysql" dbDriver="native" switchType="1" slaveThreshold="100">
<heartbeat>select user()</heartbeat>
<writeHost host="snaker_w" url="192.168.101.131:3306" user="zlz"
password="ppmoney"/>
</dataHost>
</mycat:schema>
我们使用了单库分表策略，执行sql:
SELECT a.id, a.process_Id FROM wf_hist_order a
报错： [Err] 1105 - Unknown column 'a.id' in 'field …

解决单库分表策略当sql中包含别名报:Unknown column 'alias.field' in 'field list'

---

src/main/resources/schema.dtd

用户名包含 % 的情况下配置文件 dtd NMTOKEN 不通过

---

src/main/java/io/mycat/config/model/SystemConfig.java
src/main/java/io/mycat/route/impl/DruidMycatRouteStrategy.java
src/main/resources/server.xml

1. 修复 子查询中存在关联查询的情况下,检查关联字段是否是分片字段 的问题。 
修改为 检查 关联条件中是否有 分片字段。
2. 增加 子查询中存在关联查询的情况下,检查关联字段中是否有分片字段 .默认 false。
通过在server.xml 中增加以下配置项开启
`<property name="subqueryRelationshipCheck">true</property>`

修复 子查询中存在关联查询的情况下,检查关联字段是否是分片字段 的问题

---

src/main/java/io/mycat/route/parser/druid/DruidParserFactory.java
src/main/java/io/mycat/route/parser/druid/MycatSchemaStatVisitor.java
src/main/java/io/mycat/route/parser/druid/SchemaStatVisitorFactory.java
src/test/java/io/mycat/parser/druid/MycatSchemaStatVisitorTest.java

已修正子查询加入逻辑 和 条件组合运算算法为 合并重复组合，不保留子集，只保留超集. by SvenAugustus
问题描述：
采用单元测试 MycatSchemaStatVisitorTest.test5() 
测试8层以上嵌套的sql，在本案例没提交前，发现mycat单机内存急剧飙升到700MB。
子查询达到14万之多。修正子查询逻辑后，条件组合仍达到33万之多。太恐怖了。
经分析子查询加入逻辑，以及条件组合算法有问题。
其中条件组合采用的是笛卡尔积，而条件组合目前只用于路由计算。
根据路由计算逻辑，如果 一个条件列表 是 另一个条件列表的 超集。其实计算 超集的 路由，再计算 子集的 路由就不需要。
因此，条件组合算法修正为：<合并重复组合，不保留子集，只保留超集>
单元测试MycatSchemaStatVisitorTest 通过。

解决mycat-sql解析过程中子查询和条件组合运算采用笛卡尔积导致内存急剧上升mycat假死的问题

---

src/main/java/io/mycat/backend/mysql/nio/MySQLConnection.java
src/main/java/io/mycat/config/model/SystemConfig.java
src/main/java/io/mycat/server/NonBlockingSession.java
src/main/resources/server.xml

MyCat有一个特性，就是开事务之后，如果不运行update/delete/select for update等语句的话，不会将当前连接与当前session绑定。这就会导致两次select中如果有其它的在提交的话，会出现两次同样的select不一致的现象,即不能repeatable read。当然这个特性也是有用的，可以提高性能。但是会让人很困惑，因为和直连mysql有些不同,可能会在依赖repeatable read的场景出现问题。所以做了一个开关,当server.xml的system配置了strictTxIsolation=true的时候(<property name="strictTxIsolation">true</property>)，会关掉这个特性，以保证repeatable read

 增加开关以用来禁止MyCat中开事务后出现不能repeatable read的现象

---

src/main/java/io/mycat/server/response/SelectVersionComment.java

修复控制台显示拼写错误

---

src/main/java/io/mycat/route/sequence/handler/IncrSequenceTimeHandler.java

当使用服务器本地时间戳生成全局ID时，由于时间同步导致mycat服务器时间回退，mycat会使用回退后的时间生成全局ID，并进行数据插入等操作；该操作可能导致全局ID与之前生成的重复；而 客户端/业务服务器 对此一无所知。

fix sequence duplication when clock backwards

---

src/main/java/io/mycat/backend/heartbeat/MySQLHeartbeat.java
src/main/java/io/mycat/manager/response/ShowHelp.java

目前版本发现当mysql压力大的时候,mycat对于mysql的心跳检测会一直存在异常,原因是因为						detector.setHeartbeatTimeout(this.getHeartbeatTimeout());
这个超时连接没有设置,导致所有的心跳检测一直都是超时的,导致心跳无法恢复正常.

修改mysql压力大,心跳一直无法恢复正常

---

src/main/java/io/mycat/sqlengine/mpp/RowDataPacketGrouper.java

```java
for(Integer index : rmIndexSet) {
toRow.fieldValues.remove(index);
toRow.fieldCount = toRow.fieldCount - 1;
}
```
以上的remove方法调用的是List.remove(Object o)，而非List.remove(int index)；所以无法达到删除的目的。
新实现的代码中，根据index从大到小删除，避免了元素移动使index变化导致的错误删除。

fix mergAvg for on heap merge

---

src/main/java/io/mycat/route/function/PartitionByMonth.java
src/test/java/io/mycat/route/function/PartitionByMonthTest.java

本pr只是增加了功能：场景1；外加文档说明
可设置属性：
* dateFormat  ： 日期格式化，默认为 yyyy-MM-dd
* sBeginDate  ： 开始日期，无默认值
* sEndDate   ：结束日期，无默认值
> 节点从0开始
默认设置；节点数量必须是12个，从1月~12月
* "2014-01-01" = 节点0
* "2013-01-01" = 节点0
* "2018-05-01" = 节点4
* "2019-12-01" = 节点11
sBeginDate = "2017-01-01"
该配置表示"2017-01月"是第0个节点，从该时间按月递增，无最大节点
*  "2014-01-01" = 未找到节点
*  "2017-01-01" = 节点0
*  "2017-12-01" = 节点11
*  "2018-01-01" = 节点12
*  "2018-12-01" = 节点23
sBeginDate = "2015-01-01"
sEndDate = "2015-12-01"
该配置可看成与场景1一致；场景1的配置效率更高
*  "2014-01-01" = 节点0
*  "2014-02-01" = 节点1
*  "2015-02-01" = 节点1
*  "2017-01-01" = 节点0
*  "2017-12-01" = 节点11
*  "2018-12-01" = 节点11
该配置可看成是与场景1一致
sBeginDate = "2015-01-01"
sEndDate = "2015-03-01"
该配置标识只有3个节点；很难与月份对应上；平均分散到3个节点上

功能增强，按自然月分。不用配置开始和结束时间

---

src/main/java/io/mycat/sqlengine/mpp/RowDataPacketSorter.java

MySQL的DateTime与SQL Server的DateTime不一致，SQL Server中多出3位毫秒，如果按照数字对待会导致排序错乱，需要按字符串来比较。

修复按DateTime字段排序的问题

---

src/main/java/io/mycat/config/model/TableConfig.java
src/main/java/io/mycat/route/parser/druid/DruidParserFactory.java
src/main/java/io/mycat/route/parser/druid/SqlMethodInvocationHandler.java
src/main/java/io/mycat/route/parser/druid/SqlMethodInvocationHandlerFactory.java
src/main/java/io/mycat/route/parser/druid/impl/DefaultDruidParser.java
src/main/java/io/mycat/route/parser/druid/impl/DruidInsertParser.java
src/main/java/io/mycat/route/parser/druid/impl/MysqlMethodInvocationHandler.java
src/main/java/io/mycat/route/parser/druid/impl/OracleMethodInvocationHandler.java
src/main/java/io/mycat/route/parser/druid/impl/PgsqlMethodInvocationHandler.java

1. 增加now(), sysdate(), current_timestamp(), adddate(), date_add(), subdate(), date_sub()函数的支持，包括insert语句和批量insert语句。由于目前mycat不支持update分片字段的值，故update语句未做处理。是否支持这些函数对select语句影响不大，故select语句也未做处理。
2. bug修复：表名包含关键字(如order)，子表插入数据时，会检测父表是否含有对应的记录，此时mycat发出的查询sql抛语法错误。已修正。

1.6 now() function support

---

src/main/java/io/mycat/server/NonBlockingSession.java

在做读写分离时，我们采用了以下方案，在dataHost上配置了balance=0, 默认禁用读写分离，然后只有带有/*#mycat:db_type=slave*/的语句才会被分发到readHost，希望这样逐步放开读流量可以避免全部迁移带来的影响。
<dataHost name="masterFirst" maxCon="100" minCon="50" balance="0" tempReadHostAvailable="1"
writeType="0" dbType="mysql" dbDriver="native" switchType="-1"  slaveThreshold="10">
<writeHost host=mysqla>
<readHost host=mysqlb/>
</writeHost>
....
但是测试发现部分事务会丢失记录，通过分析发现部分经过MyCAT的事务会被一条rollback回滚。经过分析，是以下模式的事务会被回滚:
1. set autocommit=0;
2. INSERT INTO tablea ...
3. /*#mycat:db_type=slave*/SELECT xx from tableb
4. COMMIT
在MySQL端看到以上序列会变为以下模式，在writeHost上
1. set autocommit=0;INSERT INTO tablea ...
2. ROLLBACK
在readHost上
1. SELECT xx from tableb
这样，插入到表tablea的数据就丢了。而此时，业务服务器，MyCAT服务器和MySQL端都无任何错误日志。
经过分析，发现是MyCAT对以上场景的处理逻辑如下
* MyCAT在一个连接到MySQL writeHost的连接内碰到一个到readHost的语句
* …

当后端连接不能在同个事务中被复用时，应该产生警告日志

---

src/main/java/io/mycat/cache/DefaultLayedCachePool.java
src/main/java/io/mycat/config/Versions.java
src/main/java/io/mycat/route/parser/druid/impl/DruidDeleteParser.java
src/main/java/io/mycat/route/parser/druid/impl/DruidUpdateParser.java

问题描述：
TableId2DataNodeCache缓存表主键到datanode的关系，当分片键不在主键上，mycat使用主键缓存，通过主键去delete一条记录（假设主键缓存命中这条记录），那么这条数据被删除后，主键缓存中该条记录的主键缓存不会及时被删除，倘若在删除了之后又插入了一条主键与该主键相同的数据，且分片键的数据改变的话，那我下次查询（假设hint主键缓存），那么mycat会按缓存中的datanode去路由你的SQL，若你新的分片键不在该datanode的话，查询结果会为空！update操作同理，若update主键后，再insert新数据时，使用的是update前的主键，也可能出现查询结果为空！
解决方法：
TableId2DataNodeCache是LayerCachePool类型，为双层CachePool，
第一层：schema_tableName，value为CachePool；第二层：key为主键值，value为datanode；
在delete/update的SQL解析时清空对应表的主键缓存；源码中没有提供通过CacheName来clearCache的方法，所以在DefaultLayerCachePool中重载了clearCache(String cacheName)的方法。

update about clear tableID2DataNodeCache when parse delete or update SQL

---

src/main/java/io/mycat/backend/heartbeat/HeartbeatSQLJob.java
src/main/java/io/mycat/backend/heartbeat/MySQLDetector.java
src/main/java/io/mycat/config/model/DataHostConfig.java
src/main/java/io/mycat/sqlengine/MultiRowSQLQueryResultHandler.java
src/main/java/io/mycat/sqlengine/OneRawSQLQueryResultHandler.java
src/main/java/io/mycat/sqlengine/SQLJob.java
src/main/java/io/mycat/statistic/DataSourceSyncRecorder.java

见
- https://dev.mysql.com/doc/refman/5.7/en/group-replication.html
- https://www.zhihu.com/question/53617036
任意满足以下条件，则视为该节点不可用
1. 节点状态不为`ON`：`CHANNEL_NAME=group_replication_applier`且`SERVICE_STATE!=ON`
2. 节点恢复数据状态为`ON`：`CHANNEL_NAME=group_replication_recovery`且`SERVICE_STATE=ON`
见：https://dev.mysql.com/doc/refman/5.7/en/group-replication-monitoring.html
修改schema配置
1. 设置`switchType=4`。见：[DataHostConfig.java#L46](https://github.com/blademainer/Mycat-Server/blob/6e7a4eb76244162ae29a35aba3fc34200b2f78ab/src/main/java/io/mycat/config/model/DataHostConfig.java#L46)
2. 设置`heartbeat`为：`select * from performance_schema.replication_connection_status` 。见：[DataHostConfig.java#L52](https://github.com/blademainer/Mycat-Server/blob/6e7a4eb76244162ae29a35aba3fc34200b2f78ab/src/main/java/io/mycat/config/m …

增加了对MySQL Group Replication的心跳检测

---

src/main/java/io/mycat/manager/handler/ZKHandler.java

通过zk reload_from_zk命令加载配置文件的时候无法正确执行，代码中对于命令的offset设置不正常。
7>>>8 后结果是0，offset为0的情况下ReloadHandler中无法正确识别命令。

修改通过zk reload_from_zk命令加载配置文件时的bug

---

.gitignore
src/main/java/io/mycat/MycatServer.java
src/main/java/io/mycat/backend/mysql/nio/MySQLConnection.java
src/main/java/io/mycat/backend/mysql/nio/handler/SimpleLogHandler.java
src/main/java/io/mycat/backend/mysql/nio/handler/SingleNodeHandler.java
src/main/java/io/mycat/net/FrontendConnection.java
src/main/java/io/mycat/net/NIOSocketWR.java
src/main/java/io/mycat/net/handler/FrontendCommandHandler.java
src/main/java/io/mycat/server/ServerQueryHandler.java
src/main/java/io/mycat/server/handler/CommandHandler.java
src/main/java/io/mycat/server/parser/ServerParse.java
src/main/java/io/mycat/server/util/SchemaUtil.java

在部分数据库工具中使用到了mysql协议中的COM_FIELD_LIST（https://dev.mysql.com/doc/internals/en/com-field-list.html）指令，本版本添加了相关指令的支持。
由于此指令不是一个查询指令，如果要测试需要通过支持mysql协议的客户端进行测试。
同时修改在多schema下部分show指令的bug。

添加针对mysql协议中COM_FIELD_LIST相关指令的支持

---

src/main/java/io/mycat/net/ConnectionException.java

后端连接有时候获取的异常信息没法很好传递到前端连接，导致实际的SQL异常，客户端无法获知。
举个例子，配置单数据单分片，其中数据库的最大连接数改为 3：   
如 Linux 修改 /etc/mysql/my.conf 以下配置
```
max_connections=3
```
重启物理数据库
模拟超过3个连接mycat,进行简单测试。
实际后端异常是 `Too many connections`，但客户端无法获知。
因此，需要改动。

fix the null message for backend connection

---

src/main/java/io/mycat/MycatServer.java
src/main/java/io/mycat/backend/BackendConnection.java
src/main/java/io/mycat/backend/jdbc/JDBCConnection.java
src/main/java/io/mycat/backend/mysql/nio/MySQLConnection.java
src/main/java/io/mycat/backend/mysql/nio/MySQLConnectionHandler.java
src/main/java/io/mycat/backend/postgresql/PostgreSQLBackendConnection.java
src/main/java/io/mycat/manager/handler/ReloadHandler.java
src/main/java/io/mycat/manager/response/ReloadConfig.java
src/main/java/io/mycat/manager/response/ReloadSqlStat.java
src/main/java/io/mycat/manager/response/ShowBackend.java
src/main/java/io/mycat/manager/response/ShowSysParam.java
src/main/java/io/mycat/route/function/PartitionByMonth.java
src/main/java/io/mycat/route/parser/ManagerParseReload.java
src/main/java/io/mycat/server/NonBlockingSession.java
src/main/java/io/mycat/server/ServerConnection.java
src/main/java/io/mycat/server/ServerQueryHandler.java
src/main/java/io/mycat/server/handler/SelectHandler.java
src/main/java/io/mycat/server/handler/SetHandler.java
src/main/java/io/mycat/server/parser/ServerParseSet.java
src/main/java/io/mycat/server/response/InformationSchemaProfilingSqlyog.java
src/test/java/io/mycat/parser/ServerParserTest.java

1.参考fix navicat增加fix sqlyog应答，下面的语句参考navicat处理方式直接应答成功
`//fix sqlyog select state, round(sum(duration),5) as `duration (summed) in sec` from information_schema.profiling where query_id = 0 group by state order by `duration (summed) in sec` desc`
2.修正按月分区函数没有指定end_date时范围条件计算的索引都是0问题，增加索引号小于0时调整为0逻辑
3.管理端口，新增支持reload @@sqlstat=open|close动态设置sql监控
4.增加设置事务只读语句支持，传递事务只读状态都后端连接，解决Cannot execute statement in a READ ONLY transaction错误.
SET SESSION TRANSACTION READ ONLY;SET SESSION TRANSACTION READ WRITE;
5.修正旧版mysql客户端发送COM_FIELD_LIST命令获取表字段信息时只有fieldEof没有RowEof包导致后面的查询语句数据解析错误问题，增加连接获取和释放日志打印信息
6.增加SET SQL_SELECT_LIMIT=N|DEFAULT语句解析，保存解析结果到前端连接，发送语句到后端查询的时候再传递到后端。防止前端设置了这个值，后端连接给其他查询语句使用返回结果被限制问题（只返回1条记录问题)。对jdbc和mysql协议已测试会传递到后端，对PostgreSQLBackendConnection暂时还不支持传递都后端数据库。

增加解析事务只读语句和设置SQL查询最大行语句支持

---

src/main/java/io/mycat/statistic/stat/SqlResultSizeRecorder.java
src/main/java/io/mycat/statistic/stat/TableStatAnalyzer.java

test case:
delete from tb1;
delete tb1 from tb1;
delete tb1 from tb1, tb2 where tb1.f1 = tb2.f1;
delete tb1 from tb1, tb2 where tb1.f1 = tb2.f1;
delete tb1, tb2 from tb1, tb2 where tb1.f1 = tb2.f1;
delete tb1 from tb1 left join tb2 on tb1.f1 = tb2.f1;
delete tb2 from tb1 left join tb2 on tb1.f1 = tb2.f1;
delete tb1, tb2 from tb1 left join tb2 on tb1.f1 = tb2.f1;
delete t1 from tb1 as t1, tb2 as t2 where t1.f1 = t2.f1;
delete t2 from tb1 as t1, tb2 as t2 where t1.f1 = t2.f1;
delete t1, t2 from tb1 as t1, tb2 as t2 where t1.f1 = t2.f1;
delete t1 from tb1 as t1 left join tb2 as t2 on t1.f1 = t2.f1;
delete t2 from tb1 as t1 left join tb2 as t2 on t1.f1 = t2.f1;
delete t1, t2 from tb1 as t1 left join tb2 as t2 on t1.f1 = t2.f1;

fix bug for statistic with delete statement:

---

src/main/java/io/mycat/backend/mysql/BindValueUtil.java
src/main/java/io/mycat/backend/mysql/PreparedStatement.java
src/main/java/io/mycat/net/mysql/ExecutePacket.java

compatible c-api and python.connector

fix bug for prepared Statement With Blob

---

src/main/java/io/mycat/route/impl/DruidMycatRouteStrategy.java
src/main/java/io/mycat/server/parser/ServerParse.java

1. 补全DESC类型分支中的循环闭环。
2. 执行浅解析时，仅匹配第一个可见起始词，一旦匹配失败，则直接将其判定为OTHER类型，防止进入其他语句类型的分支中，最终交由 Druid Parse 进行语法解析，并反馈错误信息。
3. 此修复方式对 HintSQL 的类型识别无影响。
Fixes #2498

fix: 解决因"浅解析"错误识别SQL类型导致进入了DESC类型分支的死循环问题

---

src/main/java/io/mycat/backend/BackendConnection.java
src/main/java/io/mycat/backend/jdbc/JDBCConnection.java
src/main/java/io/mycat/backend/mysql/nio/MySQLConnection.java
src/main/java/io/mycat/backend/postgresql/PostgreSQLBackendConnection.java
src/main/java/io/mycat/config/model/SystemConfig.java
src/main/java/io/mycat/manager/ManagerConnection.java
src/main/java/io/mycat/net/AIOSocketWR.java
src/main/java/io/mycat/net/AbstractConnection.java
src/main/java/io/mycat/net/BackendAIOConnection.java
src/main/java/io/mycat/net/FrontendConnection.java
src/main/java/io/mycat/net/NIOProcessor.java
src/main/java/io/mycat/net/SocketWR.java
src/main/java/io/mycat/server/NonBlockingSession.java
src/main/java/io/mycat/server/ServerConnection.java

#2527 增加流量控制功能，防止select大表导致mycat内存问题

---

src/main/java/io/mycat/net/AbstractConnection.java
src/main/java/io/mycat/net/FrontendConnection.java
src/main/java/io/mycat/net/handler/FrontendAuthenticator.java
src/main/java/io/mycat/net/mysql/AuthPacket.java
src/main/java/io/mycat/route/impl/DruidMycatRouteStrategy.java

- 1 连接参数里面出现allowMultiQueries=true，日志记录便于以后排查。PS: 完全禁用影响navicat和mysql cmd方式登陆
- 2 sql里面的带句，如“update customer set name=1;update customer set name=2”，在解析时候直接报错
- 3 AbstractConnection.cleanup() 加锁，防止并发情况下buffer多次释放，导致buffer被多个connection共用，引发数据错乱

#2589 批量Insert丢数据问题 

---

src/main/java/io/mycat/route/function/PartitionByMod.java

int类型的数值范围刚好是 -2^31——2^31-1,即-2147483648——2147483647
报错insert语句中HASH_ID的值取其String.hashCode(),刚好为-2147483648，对其math.abs(-2147483648)结果依旧为负数，即计算hashCode后取绝对值时可能会发生位数溢出，因此使用math.abs(long)来求绝对值，然后使用long来接收字符串的hashCode()的值

#2689 分片使用PartitionByMod函数插入非int类型数据时报数组下标越界异常修复

---

src/main/java/io/mycat/server/response/ShowFullTables.java

mysql> SHOW FULL TABLES FROM INFORMATION_SCHEMA LIKE 'PARAMETERS';
ERROR 1046 (HY000): No database selected
mysql>
mysql>
mysql> SHOW FULL TABLES FROM INFORMATION_SCHEMA LIKE 'PARAMETERS';
**Empty set (0.00 sec)**
mysql> SHOW FULL TABLES FROM INFORMATION_SCHEMA LIKE 'PARAMETERS';
ERROR 1046 (HY000): No database selected

#2733 修复SHOW FULL TABLES FROM INFORMATION_SCHEMA多发送一个空select包问题

---

src/main/java/io/mycat/server/response/ShowFullTables.java

Mycat通过SHOW FULL TABLES FROM 命令查询表名时，将表名name强制小写
部分mysql引擎对于表名大小写敏感，所以建议取消该限制

取消查询出的表名强制小写的限制

---

src/main/resources/log4j2.xml

通过在`log4j2.xml`中，增加`shutdownHook="disable"`，来解决在调用`init_zk_data.sh`出现的如下报错：
``` 
o2021-11-12 23:57:13 INFO JAVA_CMD=/usr/local/java/bin/java
o2021-11-12 23:57:13 INFO Start to initialize /mycat of ZooKeeper
2021-11-12 23:57:14,798 Thread-1 ERROR Unable to register shutdown hook because JVM is shutting down. java.lang.IllegalStateException: Cannot add new shutdown hook as this is not started. Current state: STOPPED
at org.apache.logging.log4j.core.util.DefaultShutdownCallbackRegistry.addShutdownCallback(DefaultShutdownCallbackRegistry.java:113)
at org.apache.logging.log4j.core.impl.Log4jContextFactory.addShutdownCallback(Log4jContextFactory.java:273)
at org.apache.logging.log4j.core.LoggerContext.setUpShutdownHook(LoggerContext.java:256)
at …
```

修复在调用bin/init_zk_data.sh时，Log4j2调用shutdown的钩子报错的问题

---

src/main/java/io/mycat/net/handler/FrontendAuthenticator.java
src/main/java/io/mycat/net/mysql/AuthPacket.java
src/main/java/io/mycat/net/mysql/AuthSwitchPacket.java

#2909 enhancement
when AuthPacket auth plugin name is null or not equal mysql_native_password
MyCAT send AuthSwitchPacket which auth method name is mysql_native_password
The next stage will deal with the same logic as before

MyCAT support MySQL 8.0 client for authenication #2909
