src/main/java/org/opencloudb/jdbc/JDBCConnection.java
src/main/java/org/opencloudb/jdbc/mongodb/MongoResultSet.java
src/main/java/org/opencloudb/jdbc/mongodb/MongoResultSetMetaData.java
src/main/java/org/opencloudb/jdbc/mongodb/MongoSQLParser.java
src/main/java/org/opencloudb/jdbc/mongodb/MongoStatement.java

1：解决mongodb 分片 排序问题
2：解决mongodb不能识别SHOW指令

解决mongodb 分片 排序问题

---

src/main/assembly/assembly-linux.xml
src/main/java/org/opencloudb/parser/druid/impl/DefaultDruidParser.java

1.修正linux环境压缩包路径问题
2.修正Druid解析器添加分片字段错误

修正Druid解析器添加分片字段错误

---

src/main/java/org/opencloudb/parser/druid/impl/DruidSelectParser.java
src/main/java/org/opencloudb/route/impl/DruidMysqlRouteStrategy.java
src/test/java/org/opencloudb/route/DruidMysqlRouteStrategyTest.java

解决druid解析器count语句问题

---

src/main/java/org/opencloudb/response/ShowVariables.java
src/main/java/org/opencloudb/server/handler/ShowHandler.java
src/main/java/org/opencloudb/server/parser/ServerParseShow.java

bugfixed:
Error happen when backend is jdbc connection. #93
https://github.com/MyCATApache/Mycat-Server/issues/93

Error happen when backend is jdbc connection. #93

---

src/main/java/org/opencloudb/mpp/DataMergeService.java
src/main/java/org/opencloudb/mpp/RowDataPacketGrouper.java
src/main/java/org/opencloudb/mpp/tmp/RowDataSorter.java
src/main/java/org/opencloudb/net/AbstractConnection.java
src/main/java/org/opencloudb/parser/druid/impl/DruidSelectParser.java
src/main/java/org/opencloudb/route/RouteResultset.java
src/main/java/org/opencloudb/route/RouteResultsetNode.java
src/main/java/org/opencloudb/route/impl/AbstractRouteStrategy.java
src/main/java/org/opencloudb/route/impl/DruidMysqlRouteStrategy.java
src/main/java/org/opencloudb/route/util/RouterUtil.java
target/.gitignore

解决group by order by问题;解决select for update问题;修改错误提示信息

解决group by order by问题;解决select for update问题;修改错误提示信息

---

src/main/java/org/opencloudb/response/ShowVariables.java
src/main/java/org/opencloudb/server/handler/ShowHandler.java
src/main/java/org/opencloudb/server/parser/ServerParseShow.java

Reverts MyCATApache/Mycat-Server#101

Revert "Error happen when backend is jdbc connection. #93"---8066和9066端口的处理逻辑可能不同

---

src/main/java/org/opencloudb/mpp/DataMergeService.java
src/main/java/org/opencloudb/mpp/tmp/RowDataSorter.java
src/main/java/org/opencloudb/parser/druid/MycatSchemaStatVisitor.java
src/main/java/org/opencloudb/parser/druid/impl/DruidSelectParser.java
src/main/java/org/opencloudb/parser/druid/impl/DruidUpdateParser.java
src/main/java/org/opencloudb/route/RouteService.java
src/main/java/org/opencloudb/route/util/RouterUtil.java
src/test/java/org/opencloudb/route/HintTest.java

fixed:#87;mycat注释兼容mysql注释

---

src/main/java/org/opencloudb/route/util/RouterUtil.java

解决druid主键in查询只匹配一个条件的问题

---

src/main/java/org/opencloudb/parser/druid/impl/DruidSelectParser.java

修正druid group by 语句字段带表名提示字段找不到的问题

修正druid group by 语句字段带表名提示字段找不到的问题

---

src/main/java/org/opencloudb/config/model/SystemConfig.java
src/main/java/org/opencloudb/interceptor/impl/StatisticsSqlInterceptor.java

暂时实现sql异步统计

---

src/main/java/org/opencloudb/jdbc/JDBCConnection.java

修复了jdbc连接事务方面的一些bug。

---

src/main/java/org/opencloudb/util/MysqlDefs.java

bugfixed: data type convert error.

data type convert error.

---

src/main/java/org/opencloudb/parser/druid/MycatSchemaStatVisitor.java
src/main/java/org/opencloudb/parser/druid/impl/DefaultDruidParser.java
src/test/java/org/opencloudb/route/DruidMysqlRouteStrategyTest.java

between语句范围路由的支持。考虑了单表、多表join、字段带别名、不带别名、select、update、delete语句类型的between条件

between语句范围路由的支持

---

src/main/java/org/opencloudb/config/loader/xml/XMLSchemaLoader.java
src/main/java/org/opencloudb/config/model/TableConfig.java
src/main/java/org/opencloudb/jdbc/JDBCDatasource.java
src/main/java/org/opencloudb/parser/druid/impl/DruidSelectParser.java
src/main/resources/schema.dtd

1：支持microsoft.sqlserver
2：解决sqlserver,oracle 查询时自动加上limit的限制
schema.xml 总表的配置加上
needAddLimit="0" 表示不需要加limit语句
sqlserver,oracle不支持limit

支持microsoft.sqlserver 

---

src/main/java/org/opencloudb/mpp/RowDataPacketGrouper.java
src/main/java/org/opencloudb/parser/druid/impl/DruidSelectParser.java

1：解决druid解析器 聚合函数没合计的错误
如：sum(requestid) as requestid, sum(factprice) as factprice from biaoben:
2：分组别名的不支持的问题 group by date_format(inputdate, '%y-%m-%d')

解决druid解析器 聚合函数没合计的错误

---

src/main/java/org/opencloudb/mpp/DataMergeService.java
src/main/java/org/opencloudb/mpp/tmp/HeapItf.java
src/main/java/org/opencloudb/mpp/tmp/MaxHeap.java
src/main/java/org/opencloudb/mpp/tmp/MinHeap.java
src/main/java/org/opencloudb/mpp/tmp/RowDataCmp.java
src/main/java/org/opencloudb/mpp/tmp/RowDataSorter.java
src/main/java/org/opencloudb/mysql/nio/handler/MultiNodeQueryHandler.java
src/main/java/org/opencloudb/parser/druid/impl/DruidSelectParser.java
src/main/java/org/opencloudb/parser/util/ParseUtil.java
src/main/java/org/opencloudb/route/RouteService.java
src/test/java/org/opencloudb/route/HintTest.java

1.统一使用MaxHeap排序，order by 语句通过比较器去处理。
2.limit语句统一交给MultiNodeQueryHandler.outputMergeResult处理。

修正多节点merge排序结果不正确bug

---

src/main/java/org/opencloudb/parser/druid/impl/DruidSelectParser.java

1.3.0.1修改order by ,group by 别名的bug

1.3.0.1修改order by ,group by 别名的bug

---

src/main/java/org/opencloudb/buffer/BufferPool.java
src/main/java/org/opencloudb/mpp/DataMergeService.java
src/main/java/org/opencloudb/mpp/RowDataPacketGrouper.java
src/main/java/org/opencloudb/mpp/tmp/HeapItf.java
src/main/java/org/opencloudb/mpp/tmp/MaxHeap.java
src/main/java/org/opencloudb/mpp/tmp/MinHeap.java
src/main/java/org/opencloudb/mpp/tmp/RowDataCmp.java
src/main/java/org/opencloudb/mpp/tmp/RowDataSorter.java
src/main/java/org/opencloudb/mysql/nio/handler/MultiNodeQueryHandler.java
src/main/java/org/opencloudb/parser/druid/MycatSchemaStatVisitor.java
src/main/java/org/opencloudb/parser/druid/impl/DefaultDruidParser.java
src/main/java/org/opencloudb/parser/druid/impl/DruidSelectParser.java
src/main/java/org/opencloudb/parser/util/ParseUtil.java
src/main/java/org/opencloudb/route/RouteResultset.java
src/main/java/org/opencloudb/route/RouteResultsetNode.java
src/main/java/org/opencloudb/route/RouteService.java
src/main/java/org/opencloudb/route/impl/AbstractRouteStrategy.java
src/main/java/org/opencloudb/route/impl/DruidMysqlRouteStrategy.java
src/main/java/org/opencloudb/route/util/RouterUtil.java
src/main/java/org/opencloudb/server/response/ShowCobarCluster.java
src/main/java/org/opencloudb/server/response/ShowCobarStatus.java
src/test/java/org/opencloudb/route/DruidMysqlRouteStrategyTest.java
src/test/java/org/opencloudb/route/HintTest.java

代码合并，1.3分支到master

---

src/main/java/demo/catlets/ShareJoin.java
src/main/java/org/opencloudb/jdbc/JDBCConnection.java
src/main/java/org/opencloudb/jdbc/JDBCDatasource.java
src/main/java/org/opencloudb/sharejoin/TableFilter.java

解决此问题https://github.com/MyCATApache/Mycat-Server/issues/141

---

src/main/java/org/opencloudb/parser/druid/impl/DruidSelectParser.java

order by 带函数的 的bug
如  order by date_format(traveldate, '%y-%m-%d')

order by 带函数的 的bug

---

src/main/java/org/opencloudb/parser/druid/impl/DruidSelectParser.java

1：order by ,group by 别名/字段的bug
2：order by  date_format(traveldate, '%y-%m-%d') 的bug

order by ,group by 别名/字段的bug

---

src/main/java/org/opencloudb/config/loader/xml/XMLSchemaLoader.java
src/test/java/org/opencloudb/route/DruidMysqlRouteStrategyTest.java
src/test/java/org/opencloudb/route/FdbRouteStrategyTest.java
src/test/resources/route/schema.xml

修改通配规则，使用：dataNode="dn$1-5,dn6,dn9"，并修改对应的单元测试代码

修改通配规则，使用：dataNode="dn$1-5,dn6,dn9"

---

src/main/java/org/opencloudb/jdbc/JDBCConnection.java
src/main/java/org/opencloudb/jdbc/JDBCDatasource.java
src/main/java/org/opencloudb/jdbc/JDBCHeartbeat.java
src/main/java/org/opencloudb/util/ResultSetUtil.java

测试支持hive 0.12 0.13.1,Spark SQL 1.2.0 1.2.1

支持hive,Spark SQL

---

src/main/java/org/opencloudb/ConfigInitializer.java
src/main/java/org/opencloudb/config/loader/xml/XMLSchemaLoader.java
src/main/java/org/opencloudb/config/model/SchemaConfig.java
src/main/java/org/opencloudb/config/model/TableConfig.java
src/main/java/org/opencloudb/parser/druid/DruidParserFactory.java

SchemaConfig,ConfigInitializer 还原

---

src/main/java/demo/catlets/ShareJoin.java
src/main/java/org/opencloudb/sharejoin/JoinParser.java
src/main/java/org/opencloudb/sharejoin/TableFilter.java

/*!mycat:catlet=demo.catlets.ShareJoin */ select * from customer
a,company b on a.company_id=b.id;
/*!mycat:catlet=demo.catlets.ShareJoin */ select a.* from customer
a,company b on a.company_id=b.id;

ShareJoin修改下面语句的报错

---

src/main/java/org/opencloudb/parser/druid/MycatSelectParser.java
src/main/java/org/opencloudb/parser/druid/impl/DruidSelectParser.java
src/main/java/org/opencloudb/route/RouteResultset.java
src/test/java/org/opencloudb/route/DruidDb2SqlParserTest.java
src/test/java/org/opencloudb/route/DruidOracleSqlParser.java
src/test/java/org/opencloudb/route/DruidOracleSqlParserTest.java
src/test/java/org/opencloudb/route/DruidPostgresqlSqlParserTest.java
src/test/java/org/opencloudb/route/DruidSqlServerSqlParserTest.java
src/test/resources/route/schema.xml

添加oracle db2 sqlserver pg单元测试，解决top 星号解析错误等

添加oracle db2 sqlserver pg单元测试，解决top 星号解析错误等

---

src/main/java/demo/catlets/BatchInsertSequence.java
src/main/java/org/opencloudb/parser/druid/DruidSequenceHandler.java
src/main/java/org/opencloudb/route/MyCATSequnceProcessor.java
src/main/java/org/opencloudb/route/handler/HintCatletHandler.java

修改：
1）MyCATSequnceProcessor.executeSeq 方法中获取sequence 由Foundation
DB方式改为Druid方式实现。
2）增加一个catlet，BatchInsertSequence支持批量插入语法自动生成sequence ID。

支持批量插入sequence生成

---

src/main/java/org/opencloudb/MycatPrivileges.java
src/main/java/org/opencloudb/config/model/SystemConfig.java
src/main/java/org/opencloudb/manager/ManagerConnectionFactory.java
src/main/java/org/opencloudb/server/ServerConnectionFactory.java
src/main/java/org/opencloudb/util/StringUtil.java
src/test/java/org/opencloudb/util/StringUtilTest.java

1、MycatPrivileges 仅在 ManagerConnectionFactory 和 ServerConnectionFactory 的 getConnection()方法中用到，无需每次建立连接都new实例；
2、MYCAT_HOME未设置时，默认为当前目录或上级目录 (只校验是否包含/conf文件夹)；
3、StringUtil增强 - 忽略注释，INSERT INTO 强校验；

MycatPrivileges单实例化 及 StringUtil增强

---

src/main/java/org/opencloudb/net/handler/FrontendCommandHandler.java
src/main/java/org/opencloudb/net/handler/LoadDataInfileHandler.java
src/main/java/org/opencloudb/server/handler/ServerLoadDataInfileHandler.java

1.优化load data数据包得识别，避免误认2.优化load data全局表，避免路由查找3.修复了一个在同一个连接上执行load data几百次会出错的bug

---

src/main/java/org/opencloudb/jdbc/JDBCConnection.java
src/main/java/org/opencloudb/jdbc/ShowVariables.java

ShowVariables.execute方法执行完毕，没有对JDBC连接释放导致，JDBC事务回滚和提交出现错误

修复issues 245 Mycat JDBC连postgresql不能支持事务提交和回滚 

---

src/main/java/org/opencloudb/mysql/CharsetUtil.java

modify charset index 45 for utf8mb4

---

src/main/java/org/opencloudb/ConfigInitializer.java
src/main/java/org/opencloudb/config/model/SystemConfig.java
src/main/java/org/opencloudb/parser/druid/DruidSequenceHandler.java
src/main/java/org/opencloudb/sequence/handler/IncrSequenceTimeHandler.java
src/main/resources/sequence_time_conf.properties

增加根据本地 基于 ： 5(机器ID)+5(业务编码)+12(重复累加))时间戳的序列生成算法
配置<property name="sequnceHandlerType">2</property>

增加时间戳的全局唯一序列

---

src/main/java/org/opencloudb/backend/PhysicalDBPool.java
src/main/java/org/opencloudb/config/loader/xml/XMLSchemaLoader.java
src/main/java/org/opencloudb/config/model/DBHostConfig.java
src/main/java/org/opencloudb/config/model/DataHostConfig.java
src/main/java/org/opencloudb/jdbc/DruidManager.java
src/main/java/org/opencloudb/jdbc/JDBCDatasource.java
src/main/resources/schema.dtd

监控语法为druid语法：
datahost 添加监控属性
filters="mergeStat,log4j"   监控方式 state统计，日志统计
logTime="10000"   监控日志输入时间（毫秒）

使用jdbc 方式连接 ， 引入 druid数据源与数据库监控 

---

src/test/java/org/opencloudb/route/DruidMysqlRouteStrategyTest.java

add TestCase:delete of global table route to every datanode defined

add TestCase:delete of global table route to every datanode defined

---

src/main/java/org/opencloudb/parser/druid/impl/DruidUpdateParser.java
src/main/java/org/opencloudb/route/util/RouterUtil.java

新增，删除 修改全局表 返回受影响的行不对(应该只计算一个节点的)

新增，删除 修改全局表 返回受影响的行不对(应该只计算一个节点的)

---

src/main/java/org/opencloudb/jdbc/JDBCHeartbeat.java

修改jdbc的心跳数据，show @@heartbeat

---

src/main/java/demo/catlets/ShareJoin.java
src/main/java/org/opencloudb/route/RouteService.java
src/main/java/org/opencloudb/sqlengine/EngineCtx.java

ShareJoin bug

---

src/main/java/org/opencloudb/mpp/DataMergeService.java
src/main/java/org/opencloudb/mpp/HavingCols.java
src/main/java/org/opencloudb/mpp/RowDataPacketGrouper.java
src/main/java/org/opencloudb/parser/druid/impl/DruidSelectParser.java
src/main/java/org/opencloudb/route/RouteResultset.java
src/main/java/org/opencloudb/route/SQLMerge.java

添加having 支持。目前只支持 =，>，<，!=，>=，<=

添加having 支持。目前只支持 =，>，<，!=，>=，<=

---

pom.xml

增加mycat私有仓库。

---

src/main/java/org/opencloudb/jdbc/sequoiadb/SequoiaDriver.java

jdbc 驱动 bug

---

src/main/java/org/opencloudb/backend/PhysicalDBPool.java

负载类型为3的逻辑为1.3.0.1分支的逻辑，与主分支有逻辑上的区别，将几种类型合并为一个方法，逻辑更加清楚，更便于维护。已经提交master分支pull request / 414

修改读操作获取负载节点的逻辑，将负载类型为1、2、3的逻辑合并为一个方法

---

pom.xml
src/main/java/io/mycat/route/function/PartitionByVelocity.java
src/main/java/io/mycat/route/util/DateUtil.java
src/main/java/io/mycat/route/util/StringUtil.java
src/main/java/io/mycat/route/util/VelocityUtil.java
src/main/resources/rule.xml
src/test/java/io/mycat/route/function/PartitionByVelocityTest.java

根据velocity模板语言分片，更加灵活方便，可以满足绝大数分片场景，当前提供的几种分片方式，基本上都可以用该方法替代，而且还更加灵活。

根据velocity模板语言分片

---

src/main/java/io/mycat/net/NIOReactor.java

 修复异常关闭连接之后。继续处理抛出null的bug。

---

src/main/java/org/opencloudb/route/impl/AbstractRouteStrategy.java
src/main/java/org/opencloudb/route/util/RouterUtil.java
src/test/java/org/opencloudb/route/DDLRouteTest.java
src/test/java/org/opencloudb/route/TestDDLTableParser.java

recover ddl bug

---

src/main/java/io/mycat/server/config/loader/zkloader/ZkDataNodeConfigLoader.java
src/main/java/io/mycat/server/config/loader/zkloader/ZkSchemaConfigLoader.java

修复文件大小写发生的编译错误。

---

src/main/java/io/mycat/route/util/RouterUtil.java
src/test/java/io/mycat/route/DDLRouteTest.java

support ddl on "drop table if exists" and defaultnode

2.0 support ddl on "drop table if exists" and defaultnode

---

.gitignore
conf/dnindex.properties
src/main/java/org/opencloudb/backend/PhysicalDBPool.java
src/main/java/org/opencloudb/config/loader/xml/XMLSchemaLoader.java
src/main/java/org/opencloudb/config/model/DBHostConfig.java
src/main/resources/log4j.xml
src/main/resources/schema.dtd
src/main/resources/schema.xml
src/main/resources/server.xml
src/test/java/org/opencloudb/config/ConfigTest.java
src/test/resources/config/rule.xml
src/test/resources/config/schema.xml
src/test/resources/log4j.xml

此处提交支持两个功能
1、读写分离权重
2、支持方便配置的 动态日期表 tableYYYYMM  、 tableYYYYMMDD

修复 读写分离不支持加权重 #470

---

src/main/java/org/opencloudb/interceptor/impl/StatSqlInterceptor.java
src/main/java/org/opencloudb/parser/ManagerParseShow.java
src/main/java/org/opencloudb/response/ShowHelp.java
src/main/java/org/opencloudb/response/ShowSQL.java
src/main/java/org/opencloudb/stat/StatFilter.java
src/main/java/org/opencloudb/stat/impl/MysqlStatFilter.java

<property
name="sqlInterceptor">org.opencloudb.interceptor.impl.StatSqlInterceptor</property>
通过 show @@sql

show @@sql  Report SQL list

---

src/main/java/org/opencloudb/handler/ShowHandler.java
src/main/java/org/opencloudb/parser/ManagerParseShow.java
src/main/java/org/opencloudb/response/ShowSysLog.java
src/main/java/org/opencloudb/util/CompressUtil.java

压缩侧代码的重构，同时增加远程查看日志的指令, 例：show @@syslog limit=10

---

src/main/assembly/bin/create_zookeeper_data.bat
src/main/assembly/bin/create_zookeeper_data.sh
src/main/java/demo/ZkCreate.java
src/main/resources/zk-create.yaml
src/test/java/io/mycat/server/config/loader/zkloader/ZookeeperLoaderTest.java

添加一个建立zk数据的脚本。

---

src/main/java/org/opencloudb/parser/util/ParseUtil.java
src/test/java/org/opencloudb/parser/ServerParserTest.java

删除解析注释时遗留的对mycat注解的特殊处理，并补充了几个unit test

---

src/main/java/org/opencloudb/config/model/DataHostConfig.java
src/main/java/org/opencloudb/handler/ShowHandler.java
src/main/java/org/opencloudb/heartbeat/DBHeartbeat.java
src/main/java/org/opencloudb/heartbeat/MySQLDetector.java
src/main/java/org/opencloudb/parser/ManagerParseHeartbeat.java
src/main/java/org/opencloudb/parser/ManagerParseShow.java
src/main/java/org/opencloudb/response/ShowDatasourceSyn.java
src/main/java/org/opencloudb/response/ShowDatasourceSynDetail.java
src/main/java/org/opencloudb/response/ShowHelp.java
src/main/java/org/opencloudb/sqlengine/OneRawSQLQueryResultHandler.java
src/main/java/org/opencloudb/statistic/DataSourceSyncRecorder.java
src/main/java/org/opencloudb/statistic/HeartbeatRecorder.java
src/test/java/org/opencloudb/parser/ManagerParserTest.java

添加 主从同步 监控 … #532
添加 主从同步 监控 … show @@datasource.synstatus show @@datasource.syndetail where name=?

添加 主从同步 监控

---

src/main/java/io/mycat/backend/PhysicalDBPool.java
src/main/java/io/mycat/route/handler/HintSchemaHandler.java
src/main/java/io/mycat/server/GenalMySQLConnection.java
src/main/java/io/mycat/server/config/loader/LocalLoader.java
src/main/java/io/mycat/server/config/node/DBHostConfig.java

rt，内容见提交记录， 这些代码在1.4上运行OK， 已经完成marge

读节点支持根据权重随机负载

---

src/main/java/org/opencloudb/net/handler/FrontendAuthenticator.java

SORRY 修复短信预警的BUG，造成编译不通过

---

src/main/java/org/opencloudb/backend/BackendConnection.java
src/main/java/org/opencloudb/jdbc/JDBCConnection.java
src/main/java/org/opencloudb/mpp/DataMergeService.java
src/main/java/org/opencloudb/mpp/RowDataPacketGrouper.java
src/main/java/org/opencloudb/mpp/RowDataPacketSorter.java
src/main/java/org/opencloudb/mpp/tmp/HeapItf.java
src/main/java/org/opencloudb/mpp/tmp/MaxHeap.java
src/main/java/org/opencloudb/mpp/tmp/MinHeap.java
src/main/java/org/opencloudb/mpp/tmp/RowDataSorter.java
src/main/java/org/opencloudb/mysql/nio/handler/MultiNodeHandler.java
src/main/java/org/opencloudb/mysql/nio/handler/MultiNodeQueryHandler.java
src/main/java/org/opencloudb/net/BackendAIOConnection.java

2、对无排序的SQL,做特别优化,避免错误的SQL消耗SQL内存
3、对要排序的SQL采取淘汰算法,将内存消耗优化为节点无关
4、优化处理超过数据总数的分页offset

1、采用list替换collection,避免分页时无效遍历

---

src/main/java/org/opencloudb/backend/PhysicalDBPool.java
src/main/java/org/opencloudb/config/loader/xml/XMLSchemaLoader.java
src/main/java/org/opencloudb/config/model/DataHostConfig.java
src/main/java/org/opencloudb/handler/ReloadHandler.java
src/main/java/org/opencloudb/handler/ShowHandler.java
src/main/java/org/opencloudb/mysql/nio/handler/MultiNodeQueryHandler.java
src/main/java/org/opencloudb/mysql/nio/handler/SingleNodeHandler.java
src/main/java/org/opencloudb/parser/ManagerParseReload.java
src/main/java/org/opencloudb/parser/ManagerParseShow.java
src/main/java/org/opencloudb/response/ReloadUserStat.java
src/main/java/org/opencloudb/response/ShowSQL.java
src/main/java/org/opencloudb/response/ShowSQLSlow.java
src/main/java/org/opencloudb/response/ShowSQLSum.java
src/main/java/org/opencloudb/route/util/RouterUtil.java
src/main/java/org/opencloudb/stat/Histogram.java
src/main/java/org/opencloudb/stat/RWStat.java
src/main/java/org/opencloudb/stat/SqlStat.java
src/main/java/org/opencloudb/stat/UserStat.java
src/main/java/org/opencloudb/stat/UserStatFilter.java
src/test/java/org/opencloudb/config/ConfigTest.java
src/test/resources/config/schema.xml

1.4 新的SQL统计 及 相关 BUG修正

---

src/main/java/org/opencloudb/route/RouteService.java
src/main/java/org/opencloudb/route/handler/HintDataNodeHandler.java
src/main/java/org/opencloudb/route/handler/HintHandlerFactory.java
src/main/java/org/opencloudb/route/util/RouterUtil.java
src/main/java/org/opencloudb/stat/UserStat.java
src/test/java/org/opencloudb/route/DDLRouteTest.java

1、增加基于datanode 的 HindHander , 2、DDLRouteTest CASE 不通过的问题修复

---

src/main/java/org/opencloudb/response/ShowSQLSum.java
src/main/java/org/opencloudb/stat/RWStat.java
src/main/java/org/opencloudb/stat/UserStat.java
src/main/resources/schema.dtd

sql.sum统计增加 并发数，显示字段名重构

---

README.md
README_Chinese.md

修改中英文 README 文件，在其中新增了mycat all in one 镜像的使用说明和下载地址

修改中英文 README 文件，在其中新增了mycat all in one 镜像的使用说明和下载地址

---

src/main/java/io/mycat/backend/PhysicalDBPool.java
src/main/java/io/mycat/route/RouteService.java
src/main/java/io/mycat/route/handler/HintDataNodeHandler.java
src/main/java/io/mycat/route/handler/HintHandlerFactory.java
src/main/java/io/mycat/route/util/RouterUtil.java
src/main/java/io/mycat/server/config/loader/LocalLoader.java
src/main/java/io/mycat/server/config/node/DataHostConfig.java
src/test/java/io/mycat/route/DDLRouteTest.java

1、新增功能可设定在写服务挂掉后，读服务依然可用， 2、DDL将结构转为大写的方式执行的BUG

---

src/main/java/demo/catlets/ZkCreate.java
src/main/java/demo/catlets/ZkDownload.java
src/main/resources/zk-create.yaml

1.4.1 ZK配置文件上传下载

---

src/main/java/org/opencloudb/handler/ReloadHandler.java
src/main/java/org/opencloudb/parser/ManagerParseReload.java
src/main/java/org/opencloudb/response/ReloadSqlSlowTime.java
src/main/java/org/opencloudb/stat/UserStat.java

调整慢SQL的时间阀值
reload @@sqlslow=10;

reload @@sqlslow=10;

---

src/main/java/org/opencloudb/mysql/nio/handler/MultiNodeQueryHandler.java

修复limit -1返回空的bug

---

src/main/java/org/opencloudb/handler/ShowHandler.java
src/main/java/org/opencloudb/parser/ManagerParseShow.java
src/main/java/org/opencloudb/response/ShowSQLHigh.java
src/main/java/org/opencloudb/stat/HighFrequencySqlAnalyzer.java
src/main/java/org/opencloudb/stat/QueryResultDispatcher.java

增加高频SQL的分析功能

---

src/main/java/org/opencloudb/parser/druid/MycatSchemaStatVisitor.java
src/main/java/org/opencloudb/parser/druid/impl/DefaultDruidParser.java
src/test/java/org/opencloudb/route/DruidMysqlRouteStrategyTest.java

fixed bug:1、update 语句带别名时路由错误 2、别名大小写导致路由错误

fixed bug:1、update 语句带别名时路由错误 2、别名大小写导致路由错误

---

src/main/java/demo/catlets/ZkCreate.java
src/test/java/org/opencloudb/config/ZkConfigTest.java

	ignore test

---

src/main/java/org/opencloudb/stat/HighFrequencySqlAnalyzer.java
src/main/java/org/opencloudb/stat/TableStatAnalyzer.java

java.lang.ClassCastException:
org.opencloudb.stat.TableStatAnalyzer$SQLParser$1 cannot be cast to
com.alibaba.druid.sql.dialect.mysql.visitor.MySqlASTVisitor

bug TableStatAnalyzer$SQLParser

---

src/main/java/demo/catlets/ZkCreate.java

initialize variable zkConfig  for line 40 NullPointerException

initialize variable zkConfig  for line 40 NullPointerException

---

src/main/java/org/opencloudb/stat/QueryResultDispatcher.java
src/main/java/org/opencloudb/stat/TableStatAnalyzer.java

SQL语句解析错误 增加 try ，SqlASTVisitorAdapter 改为 MySqlASTVisitorAdapter

---

src/main/java/org/opencloudb/config/loader/zookeeper/ZookeeperSaver.java
src/test/java/org/opencloudb/config/loader/zookeeper/ZookeeperSaverTest.java

修改保存后的文件名字

---

src/main/java/org/opencloudb/config/loader/zookeeper/ZookeeperSaver.java

删除生成的xml上的standalone

---

src/main/java/org/opencloudb/stat/TableStatAnalyzer.java

解决mycat内部统计的druid sql parse类型转换错误

---

src/main/java/org/opencloudb/stat/TableStatAnalyzer.java
src/main/java/org/opencloudb/stat/UserStat.java
src/main/java/org/opencloudb/stat/UserStatAnalyzer.java

修复 sql 统计列表 里面看到好多非业务sql问题，可能的慢sql 里面 sql执行时间不太对

---

src/main/java/io/mycat/MycatServer.java
src/main/java/io/mycat/server/MySQLFrontConnection.java
src/main/java/io/mycat/server/config/node/SystemConfig.java
src/main/java/io/mycat/server/interceptor/impl/GlobalTableUtil.java
src/main/java/io/mycat/sqlengine/MultiRowSQLQueryResultHandler.java
src/main/java/io/mycat/sqlengine/OneRawSQLQueryResultHandler.java

fix当update语句的where中有子查询时SQL拦截器无法处理的bug；
增加全局表一致性检测开关；
fix MySQLFrontConnection构造函数写反了port/localPort；
增加SQLJob返回多行结果的处理器。

fix当update语句的where中有子查询时无法处理的bug

---

src/main/java/org/opencloudb/handler/ReloadHandler.java
src/main/java/org/opencloudb/parser/ManagerParseReload.java
src/main/java/org/opencloudb/parser/util/ParseUtil.java
src/main/java/org/opencloudb/response/ReloadQueryCf.java
src/main/java/org/opencloudb/response/ReloadSqlStat.java
src/main/java/org/opencloudb/server/handler/SetHandler.java
src/main/java/org/opencloudb/stat/QueryConditionAnalyzer.java
src/main/java/org/opencloudb/stat/QueryResultDispatcher.java

默认mycat 统计分析模块为打开状态，
可通过如下指令设置关闭或打开 实时统计分析模块
reload @@sqlstat=close;
reload @@sqlstat=open;

增加控制指令，可关闭或打开实时统计分析的功能

---

src/main/java/io/mycat/net/BufferQueue.java
src/main/java/io/mycat/net/Connection.java
src/main/java/io/mycat/route/function/LatestMonthPartion.java
src/main/java/io/mycat/route/function/PartitionByVelocity.java
src/main/java/io/mycat/server/classloader/JarLoader.java
src/main/java/io/mycat/server/config/loader/ConfigInitializer.java
src/main/java/io/mycat/server/parser/ServerParseShow.java
src/main/java/io/mycat/server/sequence/IncrSequenceTimeHandler.java
src/main/java/io/mycat/util/ResultSetUtil.java
src/test/java/io/mycat/cache/TestCachePoolPerformance.java
src/test/java/io/mycat/performance/SimpleConPool.java
src/test/java/io/mycat/performance/TestMergeSelectPerf.java
src/test/java/io/mycat/performance/TestSelectPerf.java
src/test/java/io/mycat/sqlexecute/BaseSQLExeTest.java
src/test/java/io/mycat/sqlexecute/MultiThreadSequnceTest.java
src/test/java/io/mycat/sqlexecute/RollbackTest.java

This pull request is focused on resolving occurrences of Sonar rule squid:S1488 - Local Variables should not be declared and then immediately returned or thrown
You can find more information about the issue here:
https://dev.eclipse.org/sonar/coding_rules#q=squid:S1488
Please let me know if you have any questions.
Kirill Vlasov

Local Variables should not be declared and then immediately returned or thrown

---

.travis.yml
src/main/java/io/mycat/backend/PhysicalDBPool.java
src/main/java/io/mycat/backend/jdbc/mongodb/MongoSQLParser.java
src/main/java/io/mycat/backend/jdbc/sequoiadb/SequoiaSQLParser.java
src/main/java/io/mycat/backend/nio/MySQLBackendConnection.java
src/main/java/io/mycat/backend/postgresql/PostgreSQLBackendConnection.java
src/main/java/io/mycat/net/Connection.java
src/main/java/io/mycat/route/parser/druid/impl/DruidSelectOracleParser.java
src/main/java/io/mycat/route/parser/druid/impl/DruidSelectParser.java
src/main/java/io/mycat/route/parser/druid/impl/DruidSelectSqlServerParser.java
src/main/java/io/mycat/route/util/RouterUtil.java
src/main/java/io/mycat/server/config/loader/ReloadUtil.java
src/main/java/io/mycat/server/executors/MultiNodeHandler.java
src/main/java/io/mycat/server/sequence/IncrSequenceMySQLHandler.java
src/main/java/io/mycat/sqlengine/tmp/RowDataSorter.java
src/main/java/io/mycat/util/ByteUtil.java
src/test/java/io/mycat/performance/UserTableInsertJob.java
src/test/java/io/mycat/sqlexecute/BaseSQLExeTest.java

This pull request is focused on resolving occurrences of Sonar rule squid:S1125 - Literal boolean values should not be used in condition expressions
You can find more information about the issue here:
https://dev.eclipse.org/sonar/coding_rules#q=squid:S1125
Please let me know if you have any questions.
Kirill Vlasov

Literal boolean values should not be used in condition expressions

---

src/main/java/org/opencloudb/config/Versions.java
src/main/java/org/opencloudb/net/FrontendConnection.java
src/main/java/org/opencloudb/response/ShowHelp.java
src/main/java/org/opencloudb/server/handler/SetHandler.java
src/main/java/org/opencloudb/server/response/CharacterSet.java
src/main/java/org/opencloudb/util/ByteUtil.java
src/main/java/org/opencloudb/util/SetIgnoreUtil.java

1.5 实际使用中PHP用户经常会操作多个SET指令组成一个Stmt

---

src/main/java/org/opencloudb/handler/ShowHandler.java
src/main/java/org/opencloudb/mysql/nio/handler/MultiNodeQueryHandler.java
src/main/java/org/opencloudb/mysql/nio/handler/SingleNodeHandler.java
src/main/java/org/opencloudb/parser/ManagerParseShow.java
src/main/java/org/opencloudb/response/ShowSQL.java
src/main/java/org/opencloudb/response/ShowSQLHigh.java
src/main/java/org/opencloudb/response/ShowSQLSlow.java
src/main/java/org/opencloudb/response/ShowSQLSumTable.java
src/main/java/org/opencloudb/stat/HighFrequencySqlAnalyzer.java
src/main/java/org/opencloudb/stat/HostStatAnalyzer.java
src/main/java/org/opencloudb/stat/QueryConditionAnalyzer.java
src/main/java/org/opencloudb/stat/QueryResult.java
src/main/java/org/opencloudb/stat/QueryResultDispatcher.java
src/main/java/org/opencloudb/stat/QueryResultListener.java
src/main/java/org/opencloudb/stat/TableStatAnalyzer.java
src/main/java/org/opencloudb/stat/UserStatAnalyzer.java

根据用户的反馈， 修复 QueryResult 在高并发的情况下 endTime 时间有延迟的问题,  sql/high/slow/table 新增 clear 参数

---

src/main/java/org/opencloudb/route/RouteService.java

修复hint sql type 引擎的问题

---

src/main/java/org/opencloudb/response/ShowSQLHigh.java
src/main/java/org/opencloudb/stat/HighFrequencySqlAnalyzer.java
src/main/java/org/opencloudb/stat/QueryResultDispatcher.java
src/main/java/org/opencloudb/stat/SQLParserHigh.java
src/main/java/org/opencloudb/stat/SqlFrequency.java
src/main/java/org/opencloudb/stat/TableStatAnalyzer.java
src/main/java/org/opencloudb/stat/UserSqlHigh.java
src/main/java/org/opencloudb/stat/UserStat.java

高频SQL分析 加user

---

src/main/java/org/opencloudb/route/util/RouterUtil.java

修复 分片节点 第一个节点不是默认节点时候 desc table 路由到默认节点的bug 表名大写转换

	修复 分片节点 第一个节点不是默认节点时候 desc table 路由到默认节点的bug 表名大写转换

---

src/main/java/io/mycat/route/RouteService.java

也就是允许 注解前导部分中存在多个 * 和 空格 ，Hibernate 自动生成的注解会带有空格。此fix提供对其的支持。

支持： "/** !mycat: */" 和 "/** #mycat: */" 形式的注解

---

src/main/java/org/opencloudb/config/Versions.java
src/main/java/org/opencloudb/config/loader/xml/XMLSchemaLoader.java
src/main/java/org/opencloudb/config/model/TableConfig.java
src/main/java/org/opencloudb/parser/druid/impl/DruidSelectParser.java
src/main/java/org/opencloudb/route/RouteResultset.java
src/main/java/org/opencloudb/route/RouteResultsetNode.java
src/main/java/org/opencloudb/route/impl/DruidMycatRouteStrategy.java
src/main/java/org/opencloudb/route/util/RouterUtil.java
src/main/java/org/opencloudb/server/NonBlockingSession.java
src/main/resources/schema.dtd

<table name="t_order" subTables="t_order$1-2,t_order3" dataNode="dn1" rule="sharding-by-mod" ></table>
使用方式添加subTables="t_order$1-2,t_order3"

1.6 添加单库内部分表特性

---

src/main/java/org/opencloudb/config/model/SystemConfig.java
src/main/java/org/opencloudb/interceptor/impl/DefaultSqlInterceptor.java
src/main/java/org/opencloudb/route/factory/RouteStrategyFactory.java

1.5 fix DefaultSqlInterceptor中为了支持foundationdb parser而进行的字符转换，导致无法在末尾插入 \ 字符的问题。

1.5 fix DefaultSqlInterceptor中为了支持foundationdb parser而进行的字符转换，

---

src/main/java/org/opencloudb/stat/SqlFrequency.java

高频SQL平均耗时,写错了

---

src/main/java/io/mycat/buffer/BufferPool.java

去掉2.0的 throw

---

src/main/java/io/mycat/route/RouteResultset.java
src/main/java/io/mycat/route/SQLMerge.java
src/main/java/io/mycat/route/parser/druid/impl/DruidSelectParser.java
src/main/java/io/mycat/sqlengine/mpp/DataMergeService.java
src/main/java/io/mycat/sqlengine/mpp/RowDataPacketGrouper.java
src/test/java/io/mycat/route/DruidMysqlHavingTest.java

Fixed bug 753, 
select avg(id) as avg, name from customer group by name 返回[5.0, 'xx']， 
select avg(id) as avg, name from customer group by name having avg > 6; 同样返回[5.0, 'xx']
支持单节点和多节点的group having子句

1.6 Fixed bug:753

---

src/main/java/org/opencloudb/mpp/DataMergeService.java

Version
Mycat-server-1.5-RELEASE-20160309173032
Problem
从应用前端来看，给mycat发出的任何请求（不管是单节点还是多节点请求）都没有响应，当前请求并被卡住，整个mycat server处于不可以状态；打开mycat日志，发现mycat server timer线程每5分钟打印sql timeout错误，并关掉大批量的后端连接。
问题分析
打开jconsole，切换到mycat server进程监控界面，进入线程监控界面， 发现所有的businessExecutor线程都阻塞于org.opencloudb.mpp.DataMergeService的packs队列上。进入该类源码查看，可以分析出businessExecutor线程从onRowMetaData()末被触发运行， 后面用于同步处理当前MySQL返回来的行包集，以进行order、group的合并操作，直到outputMergeResult()被调用才退出本次的处理，否则一直阻塞于packs队列上，一直保持饥饿状态， 并且不会处理其他节点返回的结果集。
什么情况下导致outputMergeResult()不被调用用，通过分析发现outputMergeResult()只有在所有节点行包响应完成后才调用。想象一下，如果行包由于网络原因不能完全响应或网络中断，或查询出错，那么businessExecutor线程退出的条件就得不到满足，于是活锁就发生了，mycat就失去了一个可工作的businessExecutor线程。如果这样的情况不断发生， 最终导致businessExecutor线程池歇工；另外从代码可以看出，mycat所有的结果出来都交给了这个线程池处理（除了心跳），于是mycat就hang住了！
案例模拟 …

Fixbug: Mycat sql timeout and hang problem.

---

src/main/java/io/mycat/backend/mysql/nio/handler/MultiNodeHandler.java
src/main/java/io/mycat/backend/mysql/nio/handler/MultiNodeQueryHandler.java
src/main/java/io/mycat/sqlengine/mpp/DataMergeService.java

As mycat-1.4, mycat-1.5 problem.

Fixbug: a. Mycat hang problem b. SQL error and rollback blocked in client c. MySQL backend connection error and Mycat response OK

---

src/main/java/io/mycat/buffer/BufferPool.java
src/main/java/io/mycat/net/NIOReactor.java

Handling oom error in NIOReactor and BufferPool class.

Optimization: handling oom error in NIOReactor and BufferPool class.

---

src/main/java/io/mycat/MycatServer.java

Signed-off-by: songlin411 <linsong411@163.com>

修改timer线程模型

---

src/main/java/org/opencloudb/config/model/SystemConfig.java
src/main/java/org/opencloudb/response/ReloadSqlSlowTime.java
src/main/java/org/opencloudb/response/ShowSQLSlow.java
src/main/java/org/opencloudb/response/ShowSysParam.java
src/main/java/org/opencloudb/stat/UserStat.java
src/main/java/org/opencloudb/stat/UserStatAnalyzer.java

show @@sysparam 显示慢SQL时间阀值 
慢SQL记录IP

1.5 show @@sysparam 显示慢SQL时间阀值

---

pom.xml
src/main/java/org/opencloudb/parser/druid/impl/DruidSelectParser.java
src/main/java/org/opencloudb/route/function/PartitionByHashMod.java
src/main/resources/schema.xml
src/test/java/org/opencloudb/parser/druid/DruidSelectParserTest.java
src/test/java/org/opencloudb/route/function/PartitionByHashModTest.java

修改groupby列解析修改别名替换方式，考虑列为mysql函数并且包括带表名为参数的列
* 对于含有函数的列，不能简单地取.之后的；
* 例SQL：select h.id,DATE_FORMAT(h.times,'%b %d %Y %h:%i %p') from hotnews h GROUP BY DATE_FORMAT(h.times,'%b %d %Y %h:%i %p');

对于groupby处理的一些修改

---

pom.xml
src/main/java/io/mycat/route/function/PartitionByHashMod.java
src/main/java/io/mycat/route/parser/druid/impl/DruidSelectParser.java
src/test/java/io/mycat/parser/druid/DruidSelectParserTest.java
src/test/java/io/mycat/route/function/PartitionByHashModTest.java

修改groupby列解析修改别名替换方式，考虑列为mysql函数并且包括带表名为参数的列，添加DruidSelectParser对于groupby处理修改的单元测试，同时加入Jmockito测试框架依赖；增加哈希值取模算法与对应的单元测试

将之前对于1.5的修改归并到1.6

---

src/main/java/io/mycat/route/function/PartitionByMonth.java
src/main/java/io/mycat/route/util/RouterUtil.java
src/test/java/io/mycat/route/function/PartitionByMonthTest.java

按月分片添加结束日期（月份）从而循环使用分片,具体改动见 pull request 847
测试部分在1.6上重新做了验证
https://github.com/MyCATApache/Mycat-Server/pull/847

(port pull request #847 from branch 1.5 to 1.6)按月分片添加结束日期（月份）从而循环使用分片

---

src/main/java/demo/catlets/ShareJoin.java
src/main/java/org/opencloudb/MycatServer.java
src/main/java/org/opencloudb/MycatStartup.java
src/main/java/org/opencloudb/mysql/nio/MySQLConnection.java
src/main/java/org/opencloudb/mysql/nio/MySQLConnectionAuthenticator.java
src/main/java/org/opencloudb/mysql/nio/MySQLConnectionFactory.java
src/main/java/org/opencloudb/mysql/nio/MySQLConnectionHandler.java
src/main/java/org/opencloudb/mysql/nio/handler/DelegateResponseHandler.java
src/main/java/org/opencloudb/mysql/nio/handler/SingleNodeHandler.java
src/main/java/org/opencloudb/net/NIOConnector.java
src/main/java/org/opencloudb/server/NonBlockingSession.java
src/main/java/org/opencloudb/server/ServerConnectionFactory.java
src/main/resources/schema.xml

修改ShareJoin代码，修复 对应issue #855 的问题

修改ShareJoin代码，修复 对应issue #855 的问题

---

src/main/java/io/mycat/config/model/SystemConfig.java
src/main/java/io/mycat/manager/ManagerQueryHandler.java
src/main/java/io/mycat/manager/handler/ZKHandler.java
src/main/java/io/mycat/route/sequence/handler/DistributedSequenceHandler.java
src/main/java/io/mycat/server/NonBlockingSession.java
src/main/resources/server.xml

1. 优化DistributedSequenceHandler的适应性2. 添加分布式事务开关：
在
```
<system>
<property name="enableDistributedTransactions">false</property>
</system>
```
默认为true，在大部分目前的业务场景中，业务希望规避数据库层的分布式事务。通过这个开关，如果有分布式事务，会报错。帮助业务规避。
修改后，遇到分布式事务：
非分布式事务可正常执行：

1. 优化DistributedSequenceHandler的适应性2. 添加分布式事务开关

---

src/main/java/io/mycat/MycatServer.java
src/main/java/io/mycat/config/ConfigInitializer.java
src/main/java/io/mycat/config/Versions.java
src/main/java/io/mycat/config/model/SystemConfig.java
src/main/java/io/mycat/config/model/TableConfig.java
src/main/java/io/mycat/config/table/structure/MySQLTableStructureDetector.java
src/main/java/io/mycat/config/table/structure/TableStructureProcessor.java
src/main/java/io/mycat/route/sequence/handler/DistributedSequenceHandler.java
src/main/java/io/mycat/server/NonBlockingSession.java
src/main/java/io/mycat/sqlengine/OneRawSQLQueryResultHandler.java
src/main/java/io/mycat/statistic/CommandCount.java
version.txt

1. 优化DistributedSequenceHandler的异常抛出，丢弃不必要异常
2. 添加检查每个节点表结构功能:
1)配置方法：在server.xml中配置：
```
<server><property name="checkTableConsistency">1</property>
<property name="checkTableConsistencyPeriod">30000</property></server>
```
2)checkTableConsistency为1代表开启检查，0为关闭
3）checkTableConsistencyPeriod为周期，单位ms，不设置默认为一分钟
4）如果表结构不一致示例输出：
```
2016-05-11 15:40:18,887 [WARN ][$_NIOREACTOR-1-RW] Table [HOTNEWS] structure are not consistent!  (io.mycat.config.table.structure.MySQLTableStructureDetector$MySQLTableStructureListener:MySQLTableStructureDetector.java:87) 
2016-05-11 15:40:18,891 [WARN ][$_NIOREACTOR-1-RW] Currently detected:   (io.mycat.config.table.structure.MySQLTableStructureDetector$MySQLTableStructureListener:MySQLTableStructureDetector.java:88) 
2016-05-11 15:40:18,891 [WARN …
```

1. 优化DistributedSequenceHandler的异常抛出，丢弃不必要异常 2. 添加检查每个节点表结构功能:

---

src/main/java/io/mycat/route/sequence/handler/DistributedSequenceHandler.java

优化DistributedSequenceHandler代码

---

src/main/java/io/mycat/buffer/ByteBufferPage.java
src/main/java/io/mycat/route/parser/druid/impl/DruidSelectParser.java
src/main/resources/schema.xml

回滚schema.xml,增加解析函数列兼容性

---

src/main/java/io/mycat/buffer/ByteBufferArena.java
src/main/java/io/mycat/buffer/ByteBufferChunk.java
src/main/java/io/mycat/buffer/ByteBufferChunkList.java
src/test/java/io/mycat/buffer/TestByteBufferArena.java
src/test/java/io/mycat/buffer/TestDirectByteBufferPool.java

增加另一种Direct内存缓冲池，仿照netty

---

src/main/java/io/mycat/MycatServer.java
src/main/java/io/mycat/MycatStartup.java
src/main/java/io/mycat/route/factory/RouteStrategyFactory.java
src/main/java/io/mycat/route/impl/AbstractRouteStrategy.java
src/main/java/io/mycat/route/util/RouterUtil.java
src/main/java/io/mycat/server/ServerConnection.java
src/main/java/io/mycat/server/ServerQueryHandler.java
src/test/java/io/mycat/buffer/TestDirectByteBufferPool.java

修改RouteStrategyFactory的初始化方式，去掉了一些没有用的锁
修改需要全局ID的insert语句的执行方式，对于线程安全的全局ID生成器（3和4）直接执行语句

改善一些代码和锁，添加一些注释

---

src/test/java/io/mycat/buffer/TestByteBufferArena.java
src/test/java/io/mycat/buffer/TestDirectByteBufferPool.java
src/test/java/io/mycat/route/DruidMysqlHavingTest.java
src/test/java/io/mycat/route/DruidMysqlSqlParserTest.java
src/test/java/io/mycat/route/DruidOracleSqlParserTest.java
src/test/java/io/mycat/route/DruidPostgresqlSqlParserTest.java
src/test/java/io/mycat/route/DruidSqlServerSqlParserTest.java
src/test/java/io/mycat/route/HintDBTypeTest.java
src/test/java/io/mycat/route/HintTest.java

修改RouteStrategyFactory的单元测试方式，减少ByteBufferArena的单元测试循环次数

修改RouteStrategyFactory的单元测试方式，减少ByteBufferArena的单元测试循环次数

---

src/main/assembly/bin/dataMigrate.bat
src/main/java/io/mycat/util/dataMigrator/DataMigratorArgs.java
src/main/java/io/mycat/util/dataMigrator/DataMigratorUtil.java
src/main/java/io/mycat/util/dataMigrator/dataIOImpl/MysqlDataIO.java

mycat1.6 自动扩容缩容工具支持windows， 修复跨主机迁移数据问题

mycat1.6 自动扩容缩容工具支持windows， 修复跨主机迁移数据问题

---

src/main/java/io/mycat/server/interceptor/impl/GlobalTableUtil.java

当执行全局表创建表语句时，检查字段是否包含"_mycat_op_time"，如果不包含，为create table语句增加"_mycat_op_time"列。

当执行全局表创建表语句时，检查字段是否包含"_mycat_op_time"，如果不包含，为create table语句增加"_mycat_op_time"列。

---

src/main/java/io/mycat/memory/unsafe/Platform.java
src/main/java/io/mycat/memory/unsafe/ringbuffer/RingBuffer.java
src/main/java/io/mycat/memory/unsafe/ringbuffer/common/DataProvider.java
src/main/java/io/mycat/memory/unsafe/ringbuffer/common/event/EventFactory.java
src/main/java/io/mycat/memory/unsafe/ringbuffer/common/event/EventSequencer.java
src/main/java/io/mycat/memory/unsafe/ringbuffer/common/event/EventSink.java
src/main/java/io/mycat/memory/unsafe/ringbuffer/common/event/EventTranslator.java
src/main/java/io/mycat/memory/unsafe/ringbuffer/common/event/EventTranslatorOneArg.java
src/main/java/io/mycat/memory/unsafe/ringbuffer/common/event/EventTranslatorThreeArg.java
src/main/java/io/mycat/memory/unsafe/ringbuffer/common/event/EventTranslatorTwoArg.java
src/main/java/io/mycat/memory/unsafe/ringbuffer/common/event/EventTranslatorVararg.java

src/main/java/io/mycat/memory/unsafe/Platform.java那个文件不小心格式化了，没有修改，只是添加一些关于Unsafe的应用

	进一步实现Ringbuffer

---

src/main/java/io/mycat/memory/unsafe/Platform.java
src/main/java/io/mycat/memory/unsafe/array/CharArray.java
src/main/java/io/mycat/memory/unsafe/memory/MemoryBlock.java
src/main/java/io/mycat/memory/unsafe/memory/mm/MemoryConsumer.java

数据结构元素为String，底层是CharArray in direct buffer
修改目前未用函数命名

	进一步完成RingBuffer

---

src/main/java/io/mycat/route/parser/druid/impl/DruidInsertParser.java
src/main/java/io/mycat/route/parser/druid/impl/DruidUpdateParser.java
src/test/java/io/mycat/parser/druid/DruidUpdateParserTest.java
src/test/java/io/mycat/route/DruidMysqlRouteStrategyTest.java

具体内容见pull request 1022
https://github.com/MyCATApache/Mycat-Server/pull/1022

修改对于update语句中set子句包含分片字段更新语句的处理逻辑, 移植1.5 branch上的pr 1022

---

src/main/java/org/opencloudb/route/function/PartitionByMonth.java

对于循环的按月分片，范围查询和按天分片有类似的问题，
分片开始是2016年1月，结束是2017年12月，共24个分片
MySQL [zlpush]> explain select * from kd_inbox_uni where sys_date between 20171201 and 20180101;
ERROR 1064 (HY000): NullPointerException
修复的方法类似于https://github.com/MyCATApache/Mycat-Server/pull/1021 对按天分片的fix

按月分片，范围查询跨头尾分片出现空指针的bug，类似pull request1024对按天分片的修改

---

src/main/java/io/mycat/catlets/JoinParser.java
src/main/java/io/mycat/sqlengine/mpp/DataNodeMergeManager.java

mergeColsMap空指针报错问题

---

src/test/java/org/opencloudb/route/DQLRouteTest.java

DefaultDruidParser.buildRouteCalculateUnits方法单元测试

---

src/main/java/io/mycat/sqlengine/mpp/DataMergeService.java

改善结果集的一致性，有序性，#1018问题修复。

---

src/test/java/io/mycat/route/DQLRouteTest.java

	DefaultDruidParser.buildRouteCalculateUnits方法单元测试

---

src/main/java/io/mycat/memory/unsafe/row/UnsafeRow.java
src/main/java/io/mycat/memory/unsafe/utils/sort/RowPrefixComputer.java
src/main/java/io/mycat/sqlengine/mpp/DataNodeMergeManager.java
src/main/java/io/mycat/sqlengine/mpp/RowDataPacketGrouper.java
src/main/java/io/mycat/sqlengine/mpp/UnsafeRowGrouper.java
src/test/java/io/mycat/memory/unsafe/map/UnsafeFixedWidthAggregationMapSuite.java
src/test/java/io/mycat/memory/unsafe/row/UnsafeRowSuite.java

解决数据类型COL_TYPE_LONG和row中列为null时，引起Mycat异常

---

src/main/java/io/mycat/backend/postgresql/PostgreSQLBackendConnection.java
src/main/java/io/mycat/backend/postgresql/PostgreSQLBackendConnectionHandler.java
src/main/java/io/mycat/backend/postgresql/utils/PacketUtils.java
src/main/java/io/mycat/net/AbstractConnection.java

PostgreSQL 原生协议当数据量大时 会出现 nio 的粘包问题.

1.6 PostgreSQL 原生协议当数据量大时 会出现 nio 的粘包问题.

---

src/main/java/io/mycat/config/loader/xml/XMLSchemaLoader.java
src/main/java/io/mycat/route/MyCATSequnceProcessor.java
src/main/java/io/mycat/route/function/AbstractPartitionAlgorithm.java
src/main/java/io/mycat/route/function/AutoPartitionByLong.java
src/main/java/io/mycat/route/function/PartitionByDate.java
src/main/java/io/mycat/route/function/PartitionByFileMap.java
src/main/java/io/mycat/route/function/PartitionByHashMod.java
src/main/java/io/mycat/route/function/PartitionByJumpConsistentHash.java
src/main/java/io/mycat/route/function/PartitionByLong.java
src/main/java/io/mycat/route/function/PartitionByMod.java
src/main/java/io/mycat/route/function/PartitionByMonth.java
src/main/java/io/mycat/route/function/PartitionByMurmurHash.java
src/main/java/io/mycat/route/function/PartitionByPattern.java
src/main/java/io/mycat/route/function/PartitionByPrefixPattern.java
src/main/java/io/mycat/route/function/PartitionByRangeMod.java
src/main/java/io/mycat/route/function/PartitionByString.java
src/main/java/io/mycat/route/function/PartitionDirectBySubString.java
src/test/java/io/mycat/route/function/RuleFunctionSuitTableTest.java

为了增强系统稳定性，增加分片表节点数与对应路由算法分区数的一致性校验:
if shard table datanode size == rule function partition size => suitable
if shard table datanode size < rule function partition size => throw ConfigException
if shard table datanode size > rule function partition size => give warn log

feat : 增加分片表节点数与对应路由算法分区数一致性校验

---

src/main/java/io/mycat/backend/mysql/nio/MySQLDataSource.java
src/main/java/io/mycat/config/ConfigInitializer.java
src/main/java/io/mycat/manager/response/ReloadConfig.java

config socket链路测试，移动到 reloadConfig 中，避免对testcase产生影响

---

src/main/java/io/mycat/backend/mysql/BindValueUtil.java
src/main/java/io/mycat/backend/mysql/PreparedStatement.java
src/main/java/io/mycat/net/FrontendConnection.java
src/main/java/io/mycat/net/handler/FrontendCommandHandler.java
src/main/java/io/mycat/net/handler/FrontendPrepareHandler.java
src/main/java/io/mycat/net/mysql/ExecutePacket.java
src/main/java/io/mycat/net/mysql/LongDataPacket.java
src/main/java/io/mycat/net/mysql/ResetPacket.java
src/main/java/io/mycat/server/handler/ServerPrepareHandler.java
src/main/java/io/mycat/statistic/CommandCount.java
src/test/java/io/mycat/sqlexecute/ServerPrepareTest.java

mycat增加两个预处理语句的支持:
- COM_STMT_SEND_LONG_DATA
- COM_STMT_RESET

完善mycat对预处理的支持

---

src/main/java/io/mycat/config/loader/zookeeper/ZkCreate.java
src/main/java/io/mycat/config/loader/zookeeper/create/ConfToZkService.java
src/main/java/io/mycat/config/loader/zookeeper/create/ZkCreate.java
src/main/java/io/mycat/config/loader/zookeeper/create/comm/SeqLinkedList.java
src/main/java/io/mycat/config/loader/zookeeper/create/comm/ServiceExecInf.java
src/main/java/io/mycat/config/loader/zookeeper/create/comm/ZkProcessBase.java
src/main/java/io/mycat/config/loader/zookeeper/create/console/FlowCfg.java
src/main/java/io/mycat/config/loader/zookeeper/create/console/SysFlow.java
src/main/java/io/mycat/config/loader/zookeeper/create/flow/FlowToBinDataService.java
src/main/java/io/mycat/config/loader/zookeeper/create/flow/FlowToCacheService.java
src/main/java/io/mycat/config/loader/zookeeper/create/flow/FlowToLineService.java
src/main/java/io/mycat/config/loader/zookeeper/create/flow/FlowToNodeService.java
src/main/java/io/mycat/config/loader/zookeeper/create/flow/FlowToRuleService.java
src/main/java/io/mycat/config/loader/zookeeper/create/flow/FlowToSchemaService.java
src/main/java/io/mycat/config/loader/zookeeper/create/flow/FlowToSequenceService.java
src/main/java/io/mycat/config/loader/zookeeper/create/flow/FlowToServerService.java
src/main/resources/zk-create-2.yaml
src/main/resources/zk-create.yaml

数据已经可以通过yaml文件直接入zk，并且在发生错误后将之前的全部数据进行清除！

通过.yaml至zk的功能完成

---

src/main/java/io/mycat/MycatServer.java
src/main/java/io/mycat/backend/ConMap.java
src/main/java/io/mycat/backend/datasource/PhysicalDBPool.java
src/main/java/io/mycat/backend/datasource/PhysicalDatasource.java
src/main/java/io/mycat/config/MycatConfig.java
src/main/java/io/mycat/manager/response/ReloadConfig.java
src/main/java/io/mycat/manager/response/ShowBackendOld.java
src/main/java/io/mycat/net/NIOProcessor.java

reload @@config_all BUG修复及代码重构

---

src/main/java/io/mycat/MycatServer.java
src/main/java/io/mycat/buffer/BufferPool.java
src/main/java/io/mycat/buffer/ByteBufferArena.java
src/main/java/io/mycat/buffer/DirectByteBufferPool.java
src/main/java/io/mycat/manager/handler/ShowHandler.java
src/main/java/io/mycat/manager/response/ShowDirectMemory.java
src/main/java/io/mycat/manager/response/ShowHelp.java
src/main/java/io/mycat/memory/MyCatMemory.java
src/main/java/io/mycat/memory/unsafe/memory/mm/MemoryManager.java
src/main/java/io/mycat/memory/unsafe/memory/mm/ResultSetMemoryPool.java
src/main/java/io/mycat/route/parser/ManagerParseShow.java

添加show @@directmemory=1 or 2 ; 显示Mycat整体和线程使用DirectMemory的情况

---

src/main/java/io/mycat/server/interceptor/impl/StatisticsSqlInterceptor.java

处理关闭流问题，为日志输出增加堆栈打印

---

src/main/java/io/mycat/manager/response/ReloadConfig.java

上一次 reload @@config_all 还有未结束的事务，则本次 reload @@config_all 返回错误

---

src/main/java/io/mycat/backend/mysql/nio/MySQLConnection.java
src/main/java/io/mycat/backend/mysql/nio/handler/MultiNodeCoordinator.java
src/main/java/io/mycat/backend/mysql/nio/handler/RollbackNodeHandler.java
src/main/java/io/mycat/backend/mysql/xa/CoordinatorLogEntry.java
src/main/java/io/mycat/backend/mysql/xa/Deserializer.java
src/main/java/io/mycat/backend/mysql/xa/LogFileLock.java
src/main/java/io/mycat/backend/mysql/xa/ParticipantLogEntry.java
src/main/java/io/mycat/backend/mysql/xa/Serializer.java
src/main/java/io/mycat/backend/mysql/xa/TxState.java
src/main/java/io/mycat/backend/mysql/xa/VersionedFile.java
src/main/java/io/mycat/backend/mysql/xa/XARollbackCallback.java
src/main/java/io/mycat/backend/mysql/xa/recovery/DeserialisationException.java
src/main/java/io/mycat/backend/mysql/xa/recovery/LogException.java
src/main/java/io/mycat/backend/mysql/xa/recovery/LogReadException.java
src/main/java/io/mycat/backend/mysql/xa/recovery/LogWriteException.java
src/main/java/io/mycat/backend/mysql/xa/recovery/Repository.java
src/main/java/io/mycat/backend/mysql/xa/recovery/impl/FileSystemRepository.java
src/main/java/io/mycat/backend/mysql/xa/recovery/impl/InMemoryRepository.java
src/main/java/io/mycat/config/model/SystemConfig.java
src/main/java/io/mycat/server/NonBlockingSession.java
src/main/resources/server.xml

XA Multi-Nodes Codes

---

src/main/java/io/mycat/route/parser/druid/DruidShardingParseInfo.java
src/main/java/io/mycat/route/parser/druid/impl/DefaultDruidParser.java
src/main/java/io/mycat/route/parser/druid/impl/DruidUpdateParser.java

更新语句
`update t1
set c1 = 1
where c2 in (
select c3 from t2
);`
会被判断为多表联合更新，并抛出异常

更新语句where里带子查询会被判断为多表联合更新，并抛出异常

---

src/main/java/io/mycat/backend/mysql/nio/handler/MultiNodeHandler.java
src/main/java/io/mycat/backend/mysql/nio/handler/SingleNodeHandler.java

修复MYSQL 部分ERROR PACKET 包，造成 ERROR 2013 (HY000): Lost connection to MySQL

---

src/main/java/io/mycat/backend/datasource/PhysicalDatasource.java
src/main/java/io/mycat/config/loader/xml/XMLSchemaLoader.java
src/main/java/io/mycat/config/model/DataHostConfig.java
src/main/java/io/mycat/route/util/RouterUtil.java

This reverts commit 10fa7f90fc695bf66dc6c8d5211139c2c1f5dc56.

"1.6新任务：针对随机路由的改进 #1195""

---

src/main/resources/server.dtd

修复 server.dtd 问题

---

src/main/java/io/mycat/net/mysql/BinaryRowDataPacket.java
src/main/java/io/mycat/server/handler/ServerPrepareHandler.java

修复
-caught err:
java.lang.IllegalArgumentException: Illegal group reference
at java.util.regex.Matcher.appendReplacement(Unknown Source)
at java.util.regex.Matcher.replaceFirst(Unknown Source)
at java.lang.String.replaceFirst(Unknown Source)

修复prepare   Cannot parse "0000-00-00 00:00:00" 及 java.lang.IllegalArgumentException: Illegal group reference 异常

---

src/main/java/io/mycat/net/FrontendConnection.java
src/main/java/io/mycat/net/mysql/CommandPacket.java

rt
https://github.com/MyCATApache/Mycat-Server/issues/1072
https://github.com/MyCATApache/Mycat-Server/issues/98

fixed issues #98 #1072  及 	修复druid 解析不出来的 sql 异常

---

src/main/java/io/mycat/memory/unsafe/utils/sort/RowPrefixComputer.java
src/main/java/io/mycat/sqlengine/mpp/DataNodeMergeManager.java

fix #1225, #1226

---

src/main/java/io/mycat/config/loader/zkprocess/xmltozk/XmltoZkMain.java
src/main/java/io/mycat/config/loader/zkprocess/zktoxml/ZktoXmlMain.java
src/main/java/io/mycat/config/loader/zkprocess/zktoxml/listen/EcacheszkToxmlLoader.java
src/main/java/io/mycat/config/loader/zkprocess/zktoxml/listen/RuleszkToxmlLoader.java
src/main/java/io/mycat/config/loader/zkprocess/zktoxml/listen/SequenceTopropertiesLoader.java
src/main/java/io/mycat/config/loader/zkprocess/zktoxml/listen/ServerzkToxmlLoader.java

1，重复代码重构
2，重构watch机制利用pathcache(完成)
3，zk连接重构

进行zk的bug修改验证

---

src/main/java/org/opencloudb/stat/UserSqlHigh.java

修复 mycat-web 引起的并发问题，造成usersqlhigh IndexOutOfBoundException

---

src/main/java/io/mycat/config/loader/xml/XMLSchemaLoader.java

feature #1201 dataHost配置writeHost和readHost取名唯一性检查

---

src/main/java/io/mycat/config/MycatPrivileges.java
src/main/java/io/mycat/config/loader/xml/XMLServerLoader.java
src/main/java/io/mycat/config/model/FirewallConfig.java
src/main/java/io/mycat/manager/response/ReloadConfig.java
src/main/resources/server.xml

[需求](Issues #1275)在firewall的whitehost中可以配置主机也可以配置网段。

[需求](Issues #1275)在firewall的whitehost中可以配置主机也可以配置网段。

---

src/main/java/io/mycat/route/parser/druid/MycatSchemaStatVisitor.java
src/test/java/io/mycat/parser/druid/MycatSchemaStatVisitorTest.java

1.6分支在升级更新druid包后，无法从 /*!mycat:schema=helper1*/注释中解析出scheam:helper
附件为整个BUG的描述与重现步骤，请查阅。
[Mycat1.6版本多租户无法解析注释bug.docx](https://github.com/MyCATApache/Mycat-Server/files/672600/Mycat1.6.bug.docx)

修复mycat多租户时解析 无法从注释中解析出schema

---

src/main/java/io/mycat/buffer/DirectByteBufferPool.java
src/main/java/io/mycat/net/AbstractConnection.java
src/main/java/io/mycat/net/NIOSocketWR.java

1. FIX Ali cloud SLB connetcion cause buff memory cannot release
2. realize show @@processor; FREE_BUFFER file data

阿里云SLB探测导致mycat 不能提供服务

---

src/main/java/io/mycat/route/RouteService.java

由于hibernate兼容原因，允许注解里把冒号替换成#

---

src/main/java/io/mycat/backend/mysql/nio/handler/SingleNodeHandler.java

在schema 配置 默认dataNode 时，使用 show tables; 时 程序报错的问题。

---

src/main/java/io/mycat/MycatServer.java

RouteStrategyFactory.getRouteStrategy() return null before init,
should init before accept request

fix RouteStrategyFactory NullPointerException

---

src/main/java/io/mycat/route/util/RouterUtil.java

1: 在通过JDBC获取数据库metadata时当表是全局表时SQL路由到错误节点的问题, 导致找不到对应表的metadata.
2: 即使是全局表, 应该调用更改后的方法(getAliveRandomDataNode), 防止全局表并不存在于某个DB时而导致查询不到的问题.

解决getRandomDataNode()方法路由到错误节点的问题.

---

src/main/java/io/mycat/route/RouteResultset.java
src/main/java/io/mycat/route/parser/druid/MycatSchemaStatVisitor.java
src/main/java/io/mycat/route/parser/druid/impl/DefaultDruidParser.java
src/test/java/io/mycat/route/DruidMysqlSqlSubqueriesParserTest.java
src/test/resources/route/rule.xml
src/test/resources/route/schema.xml

对 select 子查询的 完善.

---

src/main/java/io/mycat/route/parser/druid/impl/DefaultDruidParser.java
src/test/java/io/mycat/route/DruidMysqlSqlSubqueriesParserTest.java
src/test/resources/route/rule.xml
src/test/resources/route/schema.xml

commit 或rollback 后,事务没有关闭的的问题

---

conf/dnindex.properties
src/main/java/io/mycat/backend/mysql/DataType.java
src/main/java/io/mycat/backend/mysql/nio/handler/MiddlerQueryResultHandler.java
src/main/java/io/mycat/backend/mysql/nio/handler/MiddlerResultHandler.java
src/main/java/io/mycat/backend/mysql/nio/handler/MultiNodeQueryHandler.java
src/main/java/io/mycat/backend/mysql/nio/handler/SecondHandler.java
src/main/java/io/mycat/backend/mysql/nio/handler/SecondQueryHandler.java
src/main/java/io/mycat/catlets/ShareJoin.java
src/main/java/io/mycat/config/Versions.java
src/main/java/io/mycat/config/model/rule/RuleConfig.java
src/main/java/io/mycat/route/RouteService.java
src/main/java/io/mycat/route/impl/AbstractRouteStrategy.java
src/main/java/io/mycat/route/impl/DruidMycatRouteStrategy.java
src/main/java/io/mycat/server/NonBlockingSession.java
src/main/java/io/mycat/server/ServerConnection.java
src/main/resources/log4j2.xml
version.txt

主要解决1.如果一个查询中分片规则不一致则没结果的情况 2.如果在一个查询中包含子查询，子查询中分片规则不一致的情况处理。

分片规则不一致查询不到结果的情况，以及子查询中出现分片规则不一致的处理

---

src/main/java/io/mycat/backend/mysql/nio/handler/MiddlerQueryResultHandler.java
src/main/java/io/mycat/backend/mysql/nio/handler/MiddlerResultHandler.java
src/main/java/io/mycat/backend/mysql/nio/handler/MultiNodeQueryHandler.java
src/main/java/io/mycat/catlets/ShareJoin.java
src/main/java/io/mycat/server/ServerConnection.java

之前只支持int类型，现在所有类型后都加上引号，支持多种类型

二重sql查询存在的bug,支持多种数据类型

---

src/main/java/io/mycat/backend/mysql/nio/handler/SingleNodeHandler.java

解决子查询中只有单个表时候查询结果不准确的bug

---

src/main/java/io/mycat/backend/mysql/nio/handler/MiddlerQueryResultHandler.java
src/main/java/io/mycat/backend/mysql/nio/handler/MultiNodeQueryHandler.java
src/main/java/io/mycat/backend/postgresql/PostgreSQLBackendConnection.java
src/main/java/io/mycat/sqlengine/mpp/DataNodeMergeManager.java

如subtest1 和subtest2在分片规则不一样的情况下，select * from subtest1 where account > (select max(account) from subtest2);查询出错的情况

解决二重查询时候出现聚合查询时候的bug

---

src/main/java/io/mycat/backend/mysql/nio/handler/MultiNodeQueryHandler.java
src/main/java/io/mycat/backend/postgresql/PostgreSQLBackendConnection.java
src/main/java/io/mycat/server/ServerConnection.java

解决子查询对预编译的支持中出现的bug，之前可能会有预编译执行结果存在乱码的情况。

解决子查询对预编译的支持中出现的bug

---

src/main/java/io/mycat/route/util/RouterUtil.java

代码重新整理，首先恢复到格式化之前的代码，然后重新修改提交。
支持ER子表多statment插入：
附件为问题的描述、解决方法、测试示例
[ER字表支持多语句插入.docx](https://github.com/MyCATApache/Mycat-Server/files/998220/ER.docx)

恢复格式化代码，重新提交支持ER分片多语句插入

---

src/main/java/io/mycat/backend/mysql/nio/handler/MultiNodeQueryHandler.java
src/main/java/io/mycat/backend/mysql/nio/handler/SingleNodeHandler.java
src/main/java/io/mycat/catlets/ShareJoin.java
src/main/java/io/mycat/route/impl/DruidMycatRouteStrategy.java

1.添加存在分片规则相同但是分片datanode不同的情况的子查询支持
2.解决当子查询中结果值为空的情况下报错的bug

添加存在分片规则相同但是分片datanode不同的情况的子查询支持

---

src/main/java/io/mycat/net/NIOProcessor.java

此处在高并发情况下会存在并发问题, fixed #1072  极有可能解决了 #700

---

src/main/java/io/mycat/sqlengine/mpp/UnsafeRowGrouper.java

修复非数值列 聚合操作max或min结果不正确问题

---

src/main/java/io/mycat/backend/mysql/nio/MySQLConnection.java
src/main/java/io/mycat/backend/mysql/nio/handler/CommitNodeHandler.java
src/main/java/io/mycat/backend/mysql/nio/handler/MultiNodeCoordinator.java
src/main/java/io/mycat/backend/mysql/nio/handler/RollbackNodeHandler.java
src/main/java/io/mycat/backend/postgresql/PostgreSQLBackendConnection.java
src/main/java/io/mycat/server/NonBlockingSession.java
src/main/java/io/mycat/server/ServerConnection.java
src/main/java/io/mycat/server/handler/BeginHandler.java
src/main/java/io/mycat/server/handler/SetHandler.java
src/main/java/io/mycat/server/handler/StartHandler.java

1.      #1202  1.6新任务：mycat事务兼容性改进
2.      修复单实例内有多个数据库XA事务的问题

1.6新任务：mycat事务兼容性改进

---

src/main/java/io/mycat/route/parser/druid/impl/DruidSelectParser.java
src/main/java/io/mycat/sqlengine/mpp/DataNodeMergeManager.java
src/main/java/io/mycat/sqlengine/mpp/UnsafeRowGrouper.java

1.修复 issues #1535 
2.修复having 后面跟聚合函数(max,min,count)的一系列问题

修复having 后面跟聚合函数(avg,max,min,count)的一系列问题

---

src/main/java/io/mycat/memory/unsafe/utils/sort/RowPrefixComputer.java

修复多字段排序下的bug fixes #1515

---

src/main/java/io/mycat/backend/mysql/nio/handler/CommitNodeHandler.java
src/main/java/io/mycat/backend/mysql/nio/handler/MultiNodeCoordinator.java
src/main/java/io/mycat/backend/mysql/nio/handler/RollbackNodeHandler.java
src/main/java/io/mycat/server/NonBlockingSession.java
src/main/java/io/mycat/server/ServerConnection.java
src/main/java/io/mycat/server/handler/SetHandler.java

该变量用于事务结束后,是否把autocommit 设置为之前的状态

修改变量 createNewTx 名称 为 preAcStates.

---

src/main/java/io/mycat/catlets/JoinParser.java
src/main/java/io/mycat/catlets/ShareJoin.java
src/main/java/io/mycat/catlets/TableFilter.java
src/main/java/io/mycat/sqlengine/EngineCtx.java
src/main/java/io/mycat/sqlengine/SQLJob.java

1. sql 执行过程报错时,给客户端返回错误信息.
2. where条件增加对 in 条件的支持
3. selectlist 增加对自定义函数的支持

完善 io.mycat.catlets.ShareJoin

---

src/main/java/io/mycat/catlets/ShareJoin.java

修改该问题： https://github.com/MyCATApache/Mycat-Server/issues/1563

修复 issue#1563 ShareJoin Join字段被重命名后查询报错

---

src/main/java/io/mycat/backend/jdbc/mongodb/MongoClientPropertyHelper.java
src/main/java/io/mycat/backend/jdbc/mongodb/MongoDriver.java
src/main/java/io/mycat/backend/jdbc/mongodb/MongoEmbeddedObjectProcessor.java
src/main/java/io/mycat/backend/jdbc/mongodb/MongoResultSet.java
src/test/java/io/mycat/backend/jdbc/mongodb/MongoClientPropertyHelperTest.java
src/test/java/io/mycat/backend/jdbc/mongodb/MongoEmbeddedObjectProcessorTest.java

用的时候时间转换报class cast异常
mongodb ver 3.1.x

修改一个时间类型转换错误

---

src/main/java/io/mycat/MycatServer.java
src/main/java/io/mycat/backend/ConQueue.java
src/main/java/io/mycat/migrate/MigrateDumpRunner.java
src/main/java/io/mycat/net/AbstractConnection.java
src/main/java/io/mycat/route/MyCATSequnceProcessor.java
src/main/java/io/mycat/route/parser/druid/DruidSequenceHandler.java
src/main/java/io/mycat/route/sequence/handler/IncrSequenceMySQLHandler.java
src/main/java/io/mycat/route/util/RouterUtil.java
src/main/java/io/mycat/server/NonBlockingSession.java
src/main/java/io/mycat/server/Session.java

关于自动迁移程序 booster 端 加载 dump 文件时,找不到的问题
每次dump 文件时,都会将生成的文件，放到单独的文件夹中
spath+= Thread.currentThread().getId() + System.currentTimeMillis();

修复自动迁移程序 booster 端 加载 dump 文件时,找不到的问题

---

src/main/java/io/mycat/backend/datasource/PhysicalDatasource.java
src/main/java/io/mycat/util/ResultSetUtil.java

修复ResultSetUtil 编码为GBK 的问题  修复归还连接池时,逻辑判断错误的问题.

---

src/main/java/io/mycat/backend/mysql/nio/handler/MultiNodeCoordinator.java

#1680 instanceof补全，解决oracle情况同一连接跨分片Insert等执行的应用错误： Communications link failure during commit().
mycat错误：io.mycat.backend.jdbc.JDBCConnection cannot be cast to io.mycat.backend.mysql.nio.MySQLConnection
at io.mycat.backend.mysql.nio.handler.MultiNodeCoordinator.executeBatchNodeCmd(MultiNodeCoordinator.java:61)

#1680 instanceof补全，解决oracle情况同一连接跨分片Insert等执行的应用错误

---

src/main/java/io/mycat/config/MycatPrivileges.java

解决mycat1.6.5防火墙拦截语句第二次失效问题

---

src/main/java/io/mycat/backend/datasource/PhysicalDatasource.java
src/main/java/io/mycat/catlets/ShareJoin.java

1、现象
Error querying database. Cause:java.sql.SQLException:java.lang.NumberFormatException:for intput string:"waiting for master to send event"
问题分析与Mycat心跳梳理：http://blog.csdn.net/prestigeding/article/details/78807068

1、修复在并发环境下，业务链接查询结果返回了心跳查询语句的结果。

---

src/main/java/io/mycat/route/util/RouterUtil.java

修改执行create unqie index ，分片表走默认节点的问题

修改执行create unqie index 无法创建唯一索引的问题

---

src/main/java/io/mycat/backend/datasource/PhysicalDBPool.java
src/main/java/io/mycat/backend/heartbeat/MySQLDetector.java
src/main/java/io/mycat/backend/heartbeat/MySQLHeartbeat.java
src/main/java/io/mycat/manager/response/ShowDatasourceSyn.java

When switchType == -1, allow manual switch.
When switchType == 2, allow switch when
Last_SQL_Error is empty, and
Slave_SQL_Running is Yes, and
Seconds_Behind_Master is NULL.

Change behaviour when switchType is -1 or 2

---

src/main/java/io/mycat/route/parser/druid/impl/DruidInsertParser.java

https://github.com/MyCATApache/Mycat-Server/issues/1828
修改单表分库 批量插入

支持修改单表分库批量插入

---

src/main/java/io/mycat/catlets/JoinParser.java

https://github.com/MyCATApache/Mycat-Server/issues/1850

解决 sharejoin 时 long 类型溢出的问题

---

eclipse-java-google-style.xml
intellij-java-google-style.xml

add google style

---

src/main/java/io/mycat/util/dataMigrator/DataMigratorUtil.java
src/main/java/io/mycat/util/dataMigrator/MigratorConditonFilesMaker.java

dataMigrator failed when primary key be string type, fixed it here and tested for a simple case

dataMigrator failed when primary key be string type

---

src/main/java/io/mycat/route/handler/HintDataNodeHandler.java

issues #1998 

---

src/main/java/io/mycat/backend/jdbc/mongodb/MongoSQLParser.java

对SQL向MANGO的DBObject转换过程中，支持like，in，not in的语法。

增加对LIKE，IN,NOT IN的支持。

---

src/main/java/io/mycat/route/function/PartitionByDate.java
src/main/resources/rule.xml
src/test/java/io/mycat/route/function/PartitionByDateTest.java

在保持原有按日为单位时间间隔分片能力的同时，增加了sNaturalDay 属性来支持按自然日分片。

Issues #2034 added sNaturalDay attribute to support natural day partitioning algorithm

---

README.md

Fix the invalid links

---

src/main/resources/schema.dtd

schema.dtd补充提交

---

README.md

显示格式问题&纠正错别字

---

src/main/java/io/mycat/config/loader/xml/XMLServerLoader.java
src/main/java/io/mycat/config/model/FirewallConfig.java
src/main/java/io/mycat/manager/response/ShowWhiteHost.java

考虑到用户使用习惯问题，目前@@white.set不支持多个host

白名单host支持配置多个(逗号分隔)和show @@white返回带通配符的ip

---

src/main/java/io/mycat/route/util/RouterUtil.java

如insert into test(name, date) values ("name", now())

修复使用mycat自增序列插入时values中包含函数bug

---

pom.xml
src/main/java/io/mycat/config/Versions.java
version.txt

1，maven 的一些配置信息失效，修改了下。
2，文件编码统一为 UTF-8 了。

本地下载了源码，编译运行中遇到的问题解决，方便后续有类似需求的朋友

---

src/main/java/io/mycat/memory/unsafe/Platform.java

if config item 'useOffHeapForMerge' set to 1, the condition in issue #2164 will happen.this pr will resolve this issue.

fix issue #2164

---

src/main/java/io/mycat/net/NIOConnector.java

(cherry picked from commit 12c991a)

输出连接异常remoteAddress信息，以便快速定位问题

---

src/test/java/io/mycat/util/SplitUtilTest.java

I've analysed your codebase and noticed that `io.mycat.util.SplitUtil` is not fully tested.
I've written some more tests for the methods in this class with the help of [Diffblue Cover](https://www.diffblue.com/opensource).
Hopefully, these tests will help you detect any regressions caused by future code changes. If you would find it useful to have additional tests written for this repository, I would be more than happy to look at other classes that you consider important.

Add unit tests for io.mycat.util.SplitUtil

---

src/main/java/io/mycat/net/NIOConnector.java

Reverts MyCATApache/Mycat-Server#2221

Revert "输出连接异常remoteAddress信息，以便快速定位问题"

---

src/main/java/io/mycat/backend/jdbc/JDBCHeartbeat.java

jdbc 心跳 自动切换

---

src/main/java/io/mycat/route/parser/druid/impl/DruidSelectParser.java
src/main/java/io/mycat/sqlengine/mpp/DataNodeMergeManager.java

某条mysql连接断掉会导致堆外的内存释放，这时候并发的工作线程会读取到释放的内存导致mycat宕机

mysql连接异常导致mycat的宕机

---

.vscode/launch.json
.vscode/settings.json
src/main/java/io/mycat/catlets/ShareJoin.java
src/main/java/io/mycat/catlets/TableFilter.java
src/main/java/io/mycat/net/FrontendConnection.java
src/main/java/io/mycat/route/util/RouterUtil.java
src/main/java/io/mycat/sqlengine/EngineCtx.java

修复部分bug和部分代码优化

---

src/main/java/io/mycat/net/NIOAcceptor.java
src/main/java/io/mycat/net/NIOConnector.java

#2327  OOM时守护线程不能挂，以保证OOM恢复后能继续提供服务

---

src/main/java/io/mycat/route/impl/DruidMycatRouteStrategy.java
src/main/java/io/mycat/route/util/RouterUtil.java
src/main/java/io/mycat/server/response/ShowFullTables.java
src/main/java/io/mycat/server/util/SchemaUtil.java
src/test/java/io/mycat/util/SchemaUtilTest.java

```sql
SHOW full TABLES LIKE 'table-name';
SHOW full TABLES LIKE 'c%';
SHOW TABLES LIKE '%chk';
SHOW FULL TABLES in schema-name WHERE table_type = 'BASE TABLE';
SHOW FULL TABLES FROM schema WHERE Tables_in_schema-name LIKE 'table-name'
SHOW full TABLES IN schema LIKE 'core%';
SHOW FULL TABLES   LIKE 'table_name';
```

完善show full tables 的检测语句，解决部分sql出错的问题

---

src/main/java/io/mycat/route/impl/DruidMycatRouteStrategy.java

schema.xml:
<schema name="sc_ecms" dataNode="dn_ecms"/>
<dataNode name="dn_ecms" database="ecms"/>
test case:
USE sc_ecms;
SHOW TABLES;
SHOW TABLES LIKE 't_app_node';
SHOW TABLES LIKE '%node';
SHOW TABLES LIKE 't_app%';
SHOW TABLES IN sc_ecms;
SHOW TABLES IN sc_ecms LIKE 't_app_node';
SHOW TABLES IN sc_ecms LIKE '%node';
SHOW TABLES IN sc_ecms LIKE 't_app%';
SHOW TABLES FROM sc_ecms;
SHOW TABLES FROM sc_ecms LIKE 't_app_node';
SHOW TABLES FROM sc_ecms LIKE '%node';
SHOW TABLES FROM sc_ecms LIKE 't_app%';
SHOW FULL TABLES;
SHOW FULL TABLES LIKE 't_app_node';
SHOW FULL TABLES LIKE '%node';
SHOW FULL TABLES LIKE 't_app%';
SHOW FULL TABLES IN sc_ecms;
SHOW FULL TABLES IN sc_ecms LIKE 't_app_node';
SHOW FULL TABLES IN sc_ecms LIKE '%node';
SHOW FULL TABLES IN sc_ecms LIKE 't_app%';
SHOW FULL …

fix bug for show tables from schema

---

src/main/java/io/mycat/backend/mysql/nio/handler/CommitNodeHandler.java
src/main/java/io/mycat/backend/mysql/nio/handler/MultiNodeQueryHandler.java
src/main/java/io/mycat/route/RouteResultsetNode.java
src/main/java/io/mycat/server/NonBlockingSession.java

#2528 非DDL的修改语句insert,update,delete，自动开启事务功能，避免部分成功部分失败导致的数据不一致

#2528 非DDL的修改语句insert,update,delete，自动开启事务功能

---

src/main/java/io/mycat/backend/BackendConnection.java
src/main/java/io/mycat/backend/jdbc/JDBCConnection.java
src/main/java/io/mycat/backend/mysql/nio/MySQLConnection.java
src/main/java/io/mycat/backend/postgresql/PostgreSQLBackendConnection.java
src/main/java/io/mycat/net/FrontendConnection.java
src/main/java/io/mycat/net/handler/FrontendCommandHandler.java
src/main/java/io/mycat/net/mysql/MySQLPacket.java
src/main/java/io/mycat/server/NonBlockingSession.java
src/main/java/io/mycat/server/ServerConnection.java

#2555 支持c驱动里面Mysql_reset_connection()函数，对应命令是COM_REST_CONNECTION,用于重置连接

---

src/main/java/io/mycat/backend/mysql/nio/handler/MultiNodeQueryHandler.java
src/main/java/io/mycat/backend/mysql/nio/handler/RollbackNodeHandler.java
src/main/java/io/mycat/server/NonBlockingSession.java

因之前事务代码逻辑调整，引入下面2个问题：
1、连接mysql为JDBC驱动模式下，开启事务时，DDL语句不返回
2、单节点事务，begin; update test name=? where id=1; commit; 执行commit不返回

#2635 事务2个问题修复

---

src/main/java/io/mycat/server/handler/ServerLoadDataInfileHandler.java

#2691 load data语句支持set语法设置变量

---

src/main/java/io/mycat/route/impl/DruidMycatRouteStrategy.java
src/main/java/io/mycat/server/handler/ShowHandler.java
src/main/java/io/mycat/server/parser/ServerParseShow.java
src/main/java/io/mycat/server/response/ShowFullTables.java

#2570 SHOW FULL TABLES FROM 数据名 LIKE '表名' 执行错误修复

---

src/main/java/io/mycat/route/parser/druid/MycatSchemaStatVisitor.java
src/test/java/io/mycat/route/DruidMysqlRouteStrategyTest.java

#2694 解决路由解析时候（name=1 or name=2） and id=2路由错误问题

---

src/test/java/io/mycat/statistic/TestConcurrentSafety.java

fix bug for test statistic/TestConcurrentSafety.java

---

src/main/java/io/mycat/MycatServer.java
src/main/java/io/mycat/config/model/SystemConfig.java
src/main/java/io/mycat/net/AIOAcceptor.java
src/main/java/io/mycat/net/NIOAcceptor.java
src/main/resources/server.xml

新增配置项serverBacklog，用来配置nio/aio channel的backlog数量

add backlog config

---

src/main/java/io/mycat/config/model/SystemConfig.java
src/main/java/io/mycat/manager/ManagerConnection.java
src/main/java/io/mycat/manager/ManagerConnectionFactory.java
src/main/java/io/mycat/server/ServerConnection.java
src/main/java/io/mycat/server/ServerConnectionFactory.java
src/main/resources/server.xml

add authTimeout config

---

src/main/java/io/mycat/net/FrontendConnection.java

mycat 前台连接执行SQL 由同步执行修改为异步执行
